### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by davidchase** [cujojs/most#107]
Any thoughts or oppositions against creating a recipes section, similar to maybe [gulp recipes](https://github.com/gulpjs/gulp/tree/master/docs/recipes).

 It seems like there has been a few issues about the docs or how to do something with most this could help with showing some nice implementations without needing the "whole house" (html, css, etc) as with the examples directory.

IMO, they could help "clean up" the API docs by organizing the examples into concise recipes, that way the API docs could convey the message on how use `most` and recipes would be a supplement to the API docs.

Hopefully this makes some sense

**Comment by briancavalier** [comment]
I think it makes perfect sense and would be awesome!  Do you have a few you'd like start with?

**Comment by davidchase** [comment]
I was thinking about doing a PR with a few, possibly even some that you have created in your response to questions in issues.

**Comment by briancavalier** [comment]
Sounds great.  It seems like something we can tackle very incrementally once it's been jump-started.  Looking forward to the PR :)

**Comment by davidchase** [comment]
Yes definitely, i will try to add the PR tonight, had to fix my mac :/

**Comment by briancavalier** [comment]
Ouch.  I feel you pain: I recently had the flash drive on a new macbook pro go bad beyond repair O.o

**Comment by briancavalier** [comment]
Merged.  Let's use individual issues to track new recipe ideas.

Thanks again, @davidchase, not only for suggesting it, but for writing the first 2 recipes in #113 as well.

**Comment by davidchase** [comment]
@briancavalier :+1:  any thoughts on giving them some front page love maybe on readme.md  under learn more? :smile:

**Comment by briancavalier** [comment]
> giving them some front page love

Yep, definitely!  Coming soon ...
