### ISSUE TITLE
`since` losing end signal in some cases

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#108]
Reported by @maciasello [here](https://github.com/maciasello/most/commit/fbeafde53ff9601fef898e4ae4be1842e94e8e76#commitcomment-10202783).

**Comment by briancavalier** [comment]
@maciasello Could you try the [refactor-timeslice-bounds branch](https://github.com/cujojs/most/tree/refactor-timeslice-bounds) to see if it behaves better?  I don't think it has fixed all of the issues, but may be a step in the right direction.  It also simplifies some things in `timeslice.js`, so hopefully will make things easier to debug overall.

**Comment by maciasello** [comment]
@briancavalier, it behaves better - consistently and as expected (described [here](https://github.com/maciasello/most/commit/fbeafde53ff9601fef898e4ae4be1842e94e8e76#commitcomment-10204712), confirmed [here](https://github.com/maciasello/most/commit/fbeafde53ff9601fef898e4ae4be1842e94e8e76#commitcomment-10204743)). Still only two cases examined.

**Comment by maciasello** [comment]
@briancavalier, what was the difference between the <`periodic` -> `until`> and <`unfold`> underlying streams (described [here](https://github.com/maciasello/most/commit/fbeafde53ff9601fef898e4ae4be1842e94e8e76#commitcomment-10204712)) that made it behave differently? In terms of observation they are the same.

**Comment by briancavalier** [comment]
@maciasello The difference was that `unfold` was providing it's own end condition, while in `periodic -> until`, `until` was providing the end condition (`periodic` by itself is infinite).

Thanks for verifying that the branch is an improvement!  I'll probably turn it into a PR soon.

**Comment by briancavalier** [comment]
See #110
