### ISSUE TITLE
Improve EventEmitter handling

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#116]
### Background

Most.js tries really hard to remove the possibility of zalgo at the point of observing a stream.  It does that by ensuring that an event will never be delivered to an observer in the call stack where that observer started observing.

For better or for worse, node's EventEmitter doesn't do that.  It is the emitter owner's responsibility to make any such guarantees.  For example, it is possible to write a method that creates an EventEmitter and emits events on it before the method returns, in which case those events are completely unobservable.

In *typical* usage in a non-toy node app, however, there will nearly always be a tick between creating an EventEmitter and emitting the first event on it, since that gives observers a chance to register via `on`/`addListener`.  Many times that tick will happen naturally, since the emitter is being used to notify about I/O.

### Problem

This can create confusion for developers trying out most.js for the first time with a node EventEmitter.  It's pretty reasonable for a dev to try to "see it work" by writing a simple test program like:

```js
var most = require('most');
var Emitter = require('events').EventEmitter;

var emitter = new Emitter();

most.fromEvent('foo', emitter)
	.observe(console.log);

emitter.emit('foo', 'bar');
```

It will *not* log "bar", and the developer will be confused.  Alas, [this already happened](https://twitter.com/andrew_k/status/584602761813041152).  The reason is that the `emit` is being done in the same call stack as the `observe`.  Most.js forces the subscription into the next tick, so even though it reads from top to bottom as if the observer will be setup before the `emit`, in reality, it won't be.  Thus, the observer does not see the "foo" event.

Introducing a `process.nextTick` (or any other async) will allow it to work:

```js
var most = require('most');
var Emitter = require('events').EventEmitter;

var emitter = new Emitter();

most.fromEvent('foo', emitter)
	.observe(console.log);

process.nextTick(function() {
    emitter.emit('foo', 'bar');
});
```

So, to be clear: This problem only affects events that happen in the same call stack as an observer begins observing.

### Possible solution

Conceptually, I think the solution is:

1. Always setup the observer synchronously, but
2. Never deliver events to stream observers in the same tick they begin observing.  These events must be buffered until the stack clears, then delivered.

Doing 1 will help by allowing the stream to hook up immediately to the EventEmitter, so it will not miss any events, and doing 2 will continue to prevent zalgo for stream observers.

**Comment by andrewk** [comment]
Thank you for detailing this behaviour.

While in an application it's unlikely that the async first delivery will matter, it does matter in a test environment as the author would need to explicitly wait until next tick before firing an event that will be expected. From my reading of the Possible Solutions, a test that doesn't use `setImmediate`/`process.nextTick` would still fail, as any `expect` call would be in the original call stack and the spec would complete before the event is ever delivered.

**Comment by andrewk** [comment]
The language needs work, but I'd like to request adding something like this under the `fromEvent` API docs:

> Events will not be delivered into the stream until the current call stack empties, as such it is required to wait for the next tick (eg: `process.nextTick` or `window.setTimeout`) to fire an event immediately after the `fromEvent` call and expect it to arrive in the stream.

And please also consider adding your `EventEmitter` example from the issue above to the examples directory.

**Comment by briancavalier** [comment]
@andrewk Thanks for the feedback.  I'm working on a branch that will incorporate the Possible Solution above--hopefully will push it shortly.

> From my reading of the Possible Solutions, a test that doesn't use setTimeout or process.nextTick would still fail, as any expect call would be in the original call stack and the spec would complete before the event is ever delivered

This is important.  It's very hazardous if a stream sometimes delivers events in the current call stack and sometimes doesn't.  It creates a situation where the stream consumer cannot know ahead of time if an event will occur in the same stack or not.  In the face of side-effects, this can create nondeterministic bugs that are extremely difficult to debug.  This is why promises force the stack to clear before calling handlers.

So, since it's impossible to force async streams to become sync, the only safe thing to do is force sync streams to be async.  That's the approach that most.js takes: it guarantees integrity of the call stack by ensuring that an event is never delivered in the same call stack as an observer is added. Unfortunately, as you pointed out, the current *implementation* of that approach for EventEmitter isn't great! :smile:

> The language needs work, but I'd like to request adding something like this under the fromEvent API docs

Sure, we can do that.

> And please also consider adding your EventEmitter example from the issue above to the examples directory.

In the new approach (i.e. the branch I mentioned above), it won't be necessary for a developer to add the extra `nextTick`.  IOW, it'll work more intuitively.

**Comment by briancavalier** [comment]
@andrewk See #117 and the [improve-event-emitter-subscribe branch](https://github.com/cujojs/most/tree/improve-event-emitter-subscribe).  Please give that branch a try.  It allows this to work, without `nextTick`:

```js
var most = require('most');
var Emitter = require('events').EventEmitter;

var emitter = new Emitter();

most.fromEvent('foo', emitter)
    .observe(console.log);

emitter.emit('foo', 'bar');
```

**Comment by briancavalier** [comment]
@andrewk As a part of #117, I added some info to the `most.fromEvent` docs about EventEmitter.  Between the more intuitive behavior of the code change, and the additional note in the docs, I think EventEmitter support will be in a much better spot.
