### ISSUE TITLE
create a stream of pushable collection

### ISSUE THREAD

**Issue by marcog83** [cujojs/most#132]
Hi, I love most.js when I started using this library my coding style totally changed, but I'm new in frp, so I have some troubles finding out the right pattern. I have an array, and I'd like to create a stream to observe every time an element changes. I could make a custom  a most.create and use Object.observe, but i'd like to know if there is some other way to do data-binding.
Thanks a lot for your great job

**Comment by briancavalier** [comment]
Hey @marcog83, I'm glad to hear you're enjoying most.js!

You can definitely use most.create with Object.observe.  Here's a simple example:

```js
function streamArrayChanges(array) {
    return most.create(add => {
        Object.observe(array, add);
        return () => Object.unobserve(array, add);
    });
}

let myArray = ...;
streamArrayChanges(myArray)
    .observe(arrayOfChangeRecords => console.log(arrayOfChangeRecords));
```

Each event will be the most recent batch of changes emitted by `Object.observe`.  If you want, you could also `concatMap` the batch into individual change records:

```js
function streamArrayChanges(array) {
    return most.create(add => {
        Object.observe(array, add);
        return () => Object.unobserve(array, add);
    })
    .concatMap(most.from); // unbatch the changes
}

let myArray = ...;
streamArrayChanges(myArray)
    .observe(oneChangeRecord => console.log(oneChangeRecord));
```

I also did a quick [demo of most.js + virtual dom](https://github.com/briancavalier/todomvc-fab/tree/master/examples/fabulous), which may give you some ideas.

I hope that helps!

**Comment by marcog83** [comment]
It helped a lot.
The main idea is the same, but because of cross-browser compliance i used 'observe-js' from polymer
and because I don't just add/remove elements to an array, but I re-assign the instance, 
I wrapped the array into an Object and I observe the Object property.

```javascript
var filters={
	selected:[]
};
var oFilters = most.create(add=> {
    var observer = new ObjectObserver(filters);
    observer.open((added, removed, changed, getOldValueFn) =>
	    Object.keys(changed).forEach(property=> add(changed[property]))
	);
});
```
thanks for the tip

**Comment by briancavalier** [comment]
Great, glad that helped!
