### ISSUE TITLE
switch example

### ISSUE THREAD

**Issue by marcog83** [cujojs/most#136]
Hi, I was seeing a video from Stephen Blackheath, when an example of switch feature was introduced, and i'd like to share with you a "most" port of it, because i've seen that docs doesn't have one. The sample is about a TV with 3 video streams and a remote controller that switch from a channel to another by clicking buttons.

``` javascript
 // initial white noise
var fuzz = most.from([1, 2, 3, 4, 5, 6, 7]);
// video stream from channel 1
var channel1 = most.from([11, 12, 13, 14, 15, 16, 17]);
// video stream from channel 2
var channel2 = most.from([21, 22, 23, 24, 25, 26, 27]);

// buttons click from remote controller, mapped over a video stream.
var eChannel1 = most.fromEvent("click", document.getElementById("eb1")).constant(channel1);
var eChannel2 = most.fromEvent("click", document.getElementById("eb2")).constant(channel2);
//

var sel = most.of(fuzz).merge(eChannel1, eChannel2);
var _screen =sel.switch();
//
_screen.forEach(console.log.bind(console));
```

hope it could be usefull

![switch](https://cloud.githubusercontent.com/assets/4071265/7554763/3aa0fc10-f735-11e4-814c-c155f34f84f0.png)

**Comment by briancavalier** [comment]
This is a neat little example, @marcog83, thanks for posting it!  The remote control seems like a good analogy for `switch`.  I'd love to add it to the [examples dir](https://github.com/cujojs/most/tree/master/examples).  I should have time this week to do that, but if you'd like send a PR for it, that's totally cool, too.  Let me know :)

**Comment by briancavalier** [comment]
Is [this the video](https://www.youtube.com/watch?v=gaG3tIb3Lbk) you are referring to?  Looks pretty good.  Added to my playlist :)  will watch it soon!

**Comment by marcog83** [comment]
Yep, exactly. I watched it once and I understood  few parts :). But I think that, later on my studies, with more knowledge, I could appreciate it

**Comment by briancavalier** [comment]
@marcog83 I put together a simple browser version of the example [here, in the add-switch-remote-example branch](https://github.com/cujojs/most/tree/add-switch-remote-example/examples/switch-remote).  It's basically the same, but displays in the DOM rather than console, and uses `most.periodic` to simulate a "video stream".

It can def be improved, but I think it's a good start.  What do you think?

**Comment by marcog83** [comment]
Sorry for the delay,
I like your example. I looked for some real use cases about video and controller, but it happens that video streaming is well design and changing the src attribute and play is enough :). I found some tricky stuff that add too much complexity for sample purpose, so i gave up. But looking at this site, I could see an application of switch concept. I don't know how did it. one creative guy from my agency asked me thinking about something similar. http://24hoursofhappy.com/  . This is not how they implemented it, but i though about an unique sound track and a bunch of videos (drawn into a canvas) switched and synched. Something like a combine between a clock and video streaming to get the right seek time. :) but maybe it's just my immagination

**Comment by briancavalier** [comment]
@marcog83 Right, it's not necessarily the best way to implement *actual video streams* in a browser--changing a `<video>` element's `src` attribute is a much simpler way, like you said!  However, it would certainly be a good choice for building the interactivity ... for example, you can change the src *in response to* events in a most.js stream.  That abstracts the triggering events from the implementation of how the channel is changed.  It doesn't use `switch`, but is still a fine use of event streams :)

I think the remote control example still has a lot of value in helping people understand how `switch` actually works.

> i though about an unique sound track and a bunch of videos (drawn into a canvas) switched and synched

Video and audio synchronization is a hard problem :)  It would be interesting to try it with event streams.  You could use `periodic` and `timestamp` to build a clock, and then try to sample the video and audio in at the timecodes as the clock "ticks" (emits events).  Or maybe it's just better to use the audio itself as the clock and sample the video.  I dunno if that'd work, but it'd be fun to try!

**Comment by briancavalier** [comment]
Closing, but feel free to reopen if there is more to discuss.
