### ISSUE TITLE
Please provide a dist version in repo

### ISSUE THREAD

**Issue by sporto** [cujojs/most#148]
Sometimes you just want to download a built version and just add it via script tags. Or maybe use it in JSBin via https://rawgit.com/

It would be great if you could maintain a 'dist' version in the repo, meaning a version of most.js that is ready to use in the browser by using script tags.

**Comment by briancavalier** [comment]
Hi @sporto.  Most.js works great in [RequireBin](http://requirebin.com).  Also, you can create a script tag version using browserify:

```
browserify -s most most.js --no-detect-globals -o most.build.js
```

**Comment by PhiLhoSoft** [comment]
I made this remark (as side effect...) in #146 too...

If it is so easy to do with browserify, might I suggest to include this step in your build process, and to add the result to the project? This way, we can refer to the raw listing directly on GitHub from JSFiddle, Plunker, JSBin or CodePen... These sites can be used to show off code without asking users to clone the project and run it on their machines! And can be embedded in blog posts and such. So it would be good at least for marketing purpose. :grin: 

RequireBin is useful, but it doesn't allow debugging (inlined code as base64!), and being able to use alternatives would be great.

**Comment by briancavalier** [comment]
@PhiLhoSoft good points :)  There are lots of good tools that, like it or not, still want script tags.  I didn't really think about RequireBin's lack of debugging ... that's also unfortunate.

> include this step in your build process

Right now, there is no build process :)  which is really nice.  Commit, push, tag, `npm publish`, done.  That said, adding a single step like `npm run build` probably wouldn't be too bad.  I'll probably do it :)

**Comment by briancavalier** [comment]
Actually, I'm thinking of adding a built+minified version on [jsdelivr](http://www.jsdelivr.com).  What do you think?

**Comment by briancavalier** [comment]
See #150

**Comment by PhiLhoSoft** [comment]
:+1: :smile:

**Comment by briancavalier** [comment]
This is done in #150, and it'll go out in the next release (within the next day).
