### ISSUE TITLE
Return Bluebird Promises?

### ISSUE THREAD

**Issue by jasonkuhrt** [cujojs/most#155]
I know cujo is behind `when` but since [bluebird is rather popular by now](https://github.com/luin/ioredis#features) I'm curious if there is any willingness to adopt this at the core?

**Comment by briancavalier** [comment]
It's not clear what benefit that would have.  That's in no way a knock against bluebird--it's a fine lib maintained by smart folks.  Most.js intentionally only makes the guarantee that the promises it returns are Promises/A+ and ES6 compliant.  In the future, it will be moving to a "bring your own Promise" model, so folks can use native Promise or any polyfill they want.

**Comment by jasonkuhrt** [comment]
Hm, I take this back. Composition gets us most of the way there (albeit with worse performance), e.g.:

```
@changesStream()
      .during streamTimeout 500
      .reduce F.push, []
      .then F.nth 0
      .then a.eqSet 'changes', changes
```

Bluebird takes the approach of passing data before transformer functions ala `lodash` and `underscore` which I think is misguided. Happy to see things be kept the way they are for now... : )

**Comment by briancavalier** [comment]
Cool.  Most.js is definitely tries to encourage composition and similar functional techniques :)

I'm not sure what `a.eqSet` does, but ignoring that for a sec, if you want the zeroeth event in a time window, you could probably use `take` to avoid the `reduce` + `nth` hoop jump.  For example:

```js
changesStream()
  .during(streamTimeout(500))
  .take(1)
```

**Comment by jasonkuhrt** [comment]
`a.eqSet` is `String -> Set -> Set ->  Boolean` for asserting that two sets are equivalent.

>  use take to avoid the reduce + nth hoop jump

Yep good point!

**Comment by briancavalier** [comment]
> a.eqSet is String -> Set -> Set -> Boolean for asserting that two sets are equivalent.

Ah, ok, thanks.  In that case, maybe `map`:

```js
changesStream()
  .during(streamTimeout(500))
  .take(1)
  .map(a.eqSet('changes', changes))
```

Which seems like it'd work, but leaves you in the somewhat awkward position of having a stream containing 1 boolean, and needing to use `reduce` to turn that into a promise (assuming `Promise boolean` is what you want in the end), which is not horrible, but slightly unintuitive.

I could imagine adding a combinator to deal with that, such as returning a promise for the last event in a stream:

```js
const promiseForLast = stream => stream.reduce((_, x) => x, undefined);

let s = changesStream()
  .during(streamTimeout(500))
  .take(1)
  .map(a.eqSet('changes', changes))

let last = promiseForLast(s);
```

**Comment by jasonkuhrt** [comment]
Since we're having this discussion...

Taking a step back to look at the non-special-case of `take(1)` which I think forces us to discuss the domain goal here more accurately. This is what I am currently doing:

Pardon the `coffee`, its what I write tests in right now.

```coffee
bufferStream = (stream, count) ->
  stream.take(count).reduce(F.push, [])

a.streams = (stream, xs) ->
  bufferStream(stream, xs.length).then(a.eqList(xs))
```
```coffee
describe 'foo', ->
  it 'bar', ->
    # ...
    a.streams MyStream(), [
      { foo: 1 }
      { foo: 2 }
      { foo: 3 }
    ]
    # Returns a Promise which Mocha `it` tests wait for resolution of : )

```

**Comment by jasonkuhrt** [comment]
Aside: Is there a way to add fluency to `most` such as my `beforeStream` helper above? e.g. allowing:

```
a.streams = F.curry (stream, xs) ->
  stream.buffer(xs.length).then(a.eqList(xs))
```

**Comment by briancavalier** [comment]
> Is there a way to add fluency to most

If you mean adding new prototype methods, then yeah, there are a couple options.  The `Stream` type is exposed via `most.Stream`, so you could add directly to its prototype:

```js
var Stream = require('most').Stream;

Stream.prototype.buffer = ...;
```

The usual caveats apply in that it modifies the prototype for everyone.  You could use inheritance, but right now, most.js combinators internally call `new Stream()`, which means they'll always return the super type rather than your subtype.  I guess we could switch to using `this.constructor` or `stream.constructor` to be more subtype friendly.  That might not be too bad.

**Comment by jasonkuhrt** [comment]
> modifies the prototype for everyone

This only matters for libraries I think (but that's still important, other discussion). So for my purposes now extending prototype is sufficient.

**Comment by briancavalier** [comment]
> This only matters for libraries I think

Cool, glad that'll work for you.  And yeah, as long as you're only adding new methods and no other lib does it too, you shouldn't hit any conflicts.

**Comment by jasonkuhrt** [comment]
@briancavalier I ran into a bit of trouble trying to extend `most` in my project with something trivial like https://github.com/cujojs/most/issues/156. Could you drop a code example of how that would be done?

**Comment by jasonkuhrt** [comment]
Never mind, confusion resolved https://github.com/cujojs/most/issues/156#issuecomment-129189797
