### ISSUE TITLE
most.create in chain causes later publisher call

### ISSUE THREAD

**Issue by yarray** [cujojs/most#161]
Recently timing of publisher call in most.create bothers me a bit. Following discussions in #72, I created an experiment to illustrate the problem I have:

``` javascript
var most = require('most');

let push = () => {};

let s = most.just().chain(() => most.create(add => push = add)); // print only 2
// let s = most.create(add => push = add); // print 1, 2

var tapped = s.tap(x => console.log(x));

tapped.drain();
push(1);

setTimeout(() => push(2), 0);
```

If I understand correctly the versions with and without chain should be equal in semantics. The current situation is a bit problematic for me because if I use chain, I will miss some events without the ugly `setTimeout`.

**Comment by briancavalier** [comment]
@yarray I appreciate that you provided a simplified example.  However, calling `push` right after calling `drain` isn't valid. Most.js never delivers an event on a stream in the same call stack as drain/observe/forEach is called, just as promises never invoke callbacks within the same call stack as `resolve` or `then` is called.  So the function passed to `chain` will never be called in the same call stack as `drain`.

In general, writing code outside of a stream that implicitly depends on the timing of events inside a stream is asking for trouble, just as any implicit async timing dependency is asking for trouble.  It might work by accident in some cases, but timing dependencies really should be expressed explicitly using stream combinators.

Could you explain a bit more about what your real scenario is so we can try to help?  Thanks!

**Comment by yarray** [comment]
@briancavalier I seem to understand now...  So code like

``` javascript
setTimeout(() => push(2), 0);
```

is in fact not reliable either?

I currently investigate to combine virtual dom with most.js. The hard thing is how to create event stream from dynamically added nodes. Virtual dom libraries like [snabbdom](https://github.com/paldepind/snabbdom) often provide ways to specify event handlers. However it cannot be transferred easily to stream with fromEvent. Previously I want to do something like that:

``` javascript
const clickStream = vnodeStream.map(vnode => {
    return most.create(add => {
        vnode.hook.create = (_, newNode) => {
            newNode.elm.onclick = add;
        };
    });
}).join();

clickStream.observe(e => {
    // do something
});

vnodeStream.reduce(patch);
```

The code is quite weird and with your explanation now I can tell that the weirdness comes from timing. 

I've seen your [TodoMVC example](https://github.com/briancavalier/todomvc-fab/tree/master/examples/fabulous) and it seems a possible way is to take advantage of event bubbling and listen all events on a static ancestor element. Do you think this approach is the best or perhaps the only correct way to deal with this situation?

Thanks for your reply and this awesome library.

**Comment by davidchase** [comment]
@yarray as a user of both `most` and `snabbdom` i would have to say yes that using event-delegation is ideal in the situation you present above if i understand what you are trying to achieve.. that essentially could the best way to do that regardless if you attach event listeners natively (addEventListener) or with something like `fromEvent` in `most` just my $0.02

**Comment by yarray** [comment]
@davidchase Thanks for your suggestion. The approach worked until I came across some events that do not bubble, like "focus" and "blur". There are bubbling alternatives for them but the browser support is not that good. So currently there seems no perfect solution yet...

**Comment by davidchase** [comment]
@yarray you are correct `focus` and `blur` need to be captured the opposite of bubbling and i believe the support for `focusin` and `focusout` is everywhere but mozilla as they observe some type of bug in the implementation and therefore can be poly-filled with a CustomEvent quite easily if needed

**Comment by davidchase** [comment]
you could also use `most.create` as @briancavalier suggested to manually listen to non-bubbling events

something like:
```js
var captureEventStream = function(event, source){
  return most.create(function(add, end, error) {
     source.addEventListener(event, add, true);
      return function() {
          source.removeEventListener(event, add, true);
      }
  });
};
```

**Comment by yarray** [comment]
@davidchase Thanks for your information especially the CustomEvent part. Also captureEventStream seems good but I am still not sure how to apply this method to virtual dom. Generally we can only use hook to access DOM element so it seems that we still cannot use the captured stream in proper scopes. Do you have some solutions for that?

By the way I feel the approach way too complicated. Though I also agree that ```push``` is dangerous for FRP, as discussed in #72,  it seems to be the most elegant way to handle this situation, at least for snabbdom.

**Comment by davidchase** [comment]
> vnode.hook.create = (_, newNode) => {
            newNode.elm.onclick = add;
        };

Im trying to understand your example above, but in snabbdom isnt it true you have to create the hooks objects within the hyperscript (h) in the above example i think `hook` would be `undefined` therefore it cant be done like that, no?

So we are on the same page when are you trying to add listeners (iow create the fromEvent stream) on the nodes? before you call `patch(container)` ?

**Comment by yarray** [comment]
@davidchase Yes it will not work as you observed. The example is given just to illustrate the hardness when trying to combine most's publisher and virtual dom libraries like snabbdom. As for the timing, I have not found a perfect place to attach the publisher to the hook of virtual dom. Could you please offer a more complete example if you have some successful experiences with ```captureEventStream ```?

**Comment by davidchase** [comment]
I guess im not quite following the issue... instead of using hooks why not listen to a root node and filter until you get your newly adding elements after you've patched the dom? 

Also it maybe easier if you want to chat some more on gitter about your situation to see if i can provide some help.

**Comment by yarray** [comment]
@davidchase Listening to a root node is possible (and perhaps with polyfill for focuson) is possible. However it seems a little unnecessarily complex for me (it will quickly become tedious to check what happens on the root node when the DOM hierarchy becomes more complex). Also this way the event stream will be in a callback, which may bring some inconvenience. I'd say that I prefer the approach of Elm to bind streams directly to virtual dom.

Many thanks for your suggestions about gitter. Unfortunately I am quite busy these days... Hope I can find some time and investigate more on this topic later.

**Comment by briancavalier** [comment]
@yarray I think the remaining question here is about having an imperative adapter for virtual dom.  You can use [most-subject](https://github.com/mostjs-community/subject).

Closing, but if you have more questions, please ask here or in gitter.  Thanks.
