### ISSUE TITLE
scan should not affect terminal event

### ISSUE THREAD

**Issue by jasonkuhrt** [cujojs/most#162]
Given:

```js
most.create((add, end) => {
  add(2)
  add(4)
  end(6)
})
.scan(
  (acc, x) => {
    return String(acc) + String(x)
  },
  9
)
.observe(console.log)
.then((terminal) => {
  console.log('\nterminal value:')
  console.log(terminal)
})
```

We get:

```
9
92
924

terminal value:
924
```

- Why does `9` appear on its own once?
- Why does scan never see `6`?
- Why does `then` never get `6`?

**Comment by briancavalier** [comment]
Hey @jasonkuhrt, good questions.  I'll try to tackle them individually:

> Why does 9 appear on its own once?

This is how scan is defined.  The initial value always appears in the scan.  For example, [here's how `scanl` is defined in Haskell's Data.List](https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-List.html#v:scanl)

> Why does `scan` never see 6?

In most.js, the end signal value is not "in the stream".  IOW, the values "in the stream" and the end signal value are two different classes of values, treated differently.

> Why does `then` never get 6?

Scan [substitutes the final value it sees "in the stream" as the end signal value](https://github.com/cujojs/most/blob/master/lib/combinator/accumulate.js#L56).  Looking back on this, it seems like a bug, even though it was intentionally implemented this way.  It's a breaking change, but seems pretty compelling.  We could probably do it for 0.16.

Does that help shed some light?

**Comment by jasonkuhrt** [comment]
> This is how scan is defined. The initial value always appears in the scan. For example, here's how scanl is defined in Haskell's Data.List

Ok, specifically the `q : ` cons argument see in https://hackage.haskell.org/package/base-4.8.1.0/docs/src/GHC.List.html#scanl:

```haskell
scanlGo f q ls    = q : (case ls of
```

> In most.js, the end signal value is not "in the stream". IOW, the values "in the stream" and the end signal value are two different classes of values, treated differently.

Makes sense, was just checking my intuition was right here. Sounds good.


> Looking back on this, it seems like a bug, even though it was intentionally implemented this way. It's a breaking change, but seems pretty compelling. We could probably do it for 0.16.

Yeah lets if possible. I think the reason this should be considered a bug is because of the definition of the terminal event apart from streamed values:

> the values "in the stream" and the end signal value are two different classes of values, treated differently.

Thanks for the clarifications! The initial value being appended to the result of `scan` seems surprising but I'm essentially accepting of it if that's the standard for `scan` (I'm just not very experienced with scan is all).

I'll rename this issue to be focused on fixing the identified bug.

**Comment by briancavalier** [comment]
> I think the reason this should be considered a bug is because of the definition of the terminal event apart from streamed values

Agreed

> I'll rename this issue to be focused on fixing the identified bug.

Perfect, thanks!

I'll send a PR for this shortly, so you can try it out.
