### ISSUE TITLE
Equivalent to Rx.Subject

### ISSUE THREAD

**Issue by TylorS** [cujojs/most#164]
Hello everyone, I'm new to most and I was wondering if there is an equivalent to Rx's Subject?
In particular, I'm curious if there is a way for recreating `Rx.ReplaySubject`

For some more information on what I'm trying to accomplish.

I'm trying to rewrite Cycle.js using Most instead of RxJs. I haven't been able to find a way to recreate the circular dependency between Observables.

In Cycle.js it's roughly like this (although a little more complex)
```js
const sinksProxy = new Rx.Subject()
const sources = driverFn( sinkProxy )
const sinks = application( sources )
sinks.subscribe( value => sinksProxy.onNext(value) )
```

Thanks in advance!

**Comment by TylorS** [comment]
In particular, I'm curious if there is a way for recreating `Rx.ReplaySubject`

**Comment by briancavalier** [comment]
Hey @TylorS, this is a really interesting situation--one I've not really thought about before.  I'd love to find a way to do it declaratively, rather than having to subscribe and feed the events back in.  It's totally not obvious how to do it declaratively right now, though (but I'll give it more thought!)

Anyway, I think it would be annoying to try to do it in the current version of most.js.  There's been some previous discussion about providing an externalized imperative event pushing api in #72.  That PR is a bit long in the tooth, and should probably be abandoned, but the idea certainly seems like it'd work for what you're doing in that sample code.

One question: How do external events make their way into the cycle?  Does someone (perhaps code inside `driverFn` or `application` end up calling `sinkProxy.onNext`?

I went back and forth on adding an API like that, since it tends to either put the burden managing race conditions on the caller, or introduce inefficiency if you force every event to be queued and sent in a future call stack.  But I've made my peace with it :)

Would it work for you if there were some new API that looked like:

```js
import most from 'most';
const { sink, stream } = most.whatever();

sink.add(x); // add x to stream
```

Thoughts?

**Comment by TylorS** [comment]
Thank you for such a quick and informative reply! I'm in a time crunch right now, but that API would definitely work. I simply need a way to replicate one stream into another.

I actually have a working implementation here https://github.com/tylors/cycle-more if you're interested in how it all works.

Thanks again!

**Comment by briancavalier** [comment]
Cool, thanks for the pointer.  Looks pretty interesting so far--I think I need to learn more about cycle.js to fully grok it :)

In the past, I've used a higher order stream which is then either `join`ed (if you want merge) or `switch`ed (if you want replacement) to achieve plug/unplug style functionality.  I don't know if that will work for you, but it's quite a nice pattern because it can be completely declarative.

**Comment by TylorS** [comment]
I'm home from work now! I really do agree with you that I'd love to find a *clean* way to solve this problem. I'm new to functional/reactive programming (and programming in general) and I still need to learn *most* better and grok it's code base some more before I feel I'd be in a good position to make many suggestions. I really do like the way your suggestion looks though.

```js
const { sink, stream } = most.whatever()
```

Thanks for the link to issue #72, I couldn't find that on my own. I will likely use that kind of implementation going forward. But I would love to find a better solution to be in *most* itself of course.

With the higher order stream I'm not sure I follow how that would work in my current case, if at all. I'd love to be shown I'm wrong though :+1:

**Comment by briancavalier** [comment]
> I'm not sure I follow how that would work in my current case

No worries.  I'm not sure either :) since I'm not yet familiar enough with cycle.js.  Here's a quick sketch of how it works in the general case, though.

```js
const { sink, stream } = most.whatever();
const bus = stream.join();

// "Plug" streams by emitting them as events.
// The join() above will merge anotherStream's events into bus.
// anotherStream "unplugs" itself when it ends, *or*
// you could use .until(), .during(), .takeWhile(), .take() to declaratively
// establish when anotherStream will end (and thus "unplug" itself)
sink.event(anotherStream);
```

**Comment by TylorS** [comment]
Awesome, I'm going to give that a shot right now! That looks like it will do precisely what I need :+1:

**Comment by TylorS** [comment]
Doing the following
```js
let { sink, stream } = most.empty();
stream.join(); 
```
I get `TypeError: Cannot read property 'join' of undefined`

**Comment by briancavalier** [comment]
I think my example was misleading. Sorry about that! The most.whatever api doesn't exist yet. Existing apis like empty just return a stream. I'm proposing that we create a new api that will return a sink,stream pair.

I'll whip up a quick version of this new api for you to try out later today.

**Comment by TylorS** [comment]
Awesome, I came to that conclusion the hard way.I was trying to find the part of *most* that did that, and obviously couldn't do so! :smile:

**Comment by Frikki** [comment]
@briancavalier 
> How do external events make their way into the cycle? Does someone (perhaps code inside `driverFn` or `application` end up calling `sinkProxy.onNext`?

Subscription and `onNext` are called in the *cycle-core*. It connects the data flow in a unidirectional cycle, a feedback loop, using drivers that are functions and can produce side effects and `main()` which is the actual closed-world program function. In @TylorS code, `application()` is equal to `main()`.

**Comment by briancavalier** [comment]
I haven't had a chance to put together code for you to try.  I had a thought, though.  Have you looked at to using [`most.create`](https://github.com/cujojs/most/blob/master/docs/api.md#mostcreate) to create the cycle?  Maybe something like:

```js
const s = most.create(add => {
    const sources = driverFn( add )
    const sinks = application( sources )
    sinks.subscribe(add);
});
```

I admit I don't know what `driverFn` and `application` do, but figured this might be worth discussing.  Would something like that work?

**Comment by TylorS** [comment]
Unfortunately that wouldn't work in my case without doing something like
```js
let _add;
most.create( add => {
  _add = add;
  ...
})
```
Which is an eye sore to say the least, and I only want the *most* :wink: Sorry for the really bad pun lol

If you ever have the time, the source code for my most.js version of Cycle is only 100 lines of code in 2 files. You could likely see something I couldn't. If you don't have the time or desire no worries though. https://github.com/TylorS/cycle-more/tree/master/src

As of right now I have it *working* but it doesn't feel warm and fuzzy.

**Comment by briancavalier** [comment]
Sorry this wasn't clear, but "exporting" the `add` function out of create isn't really the intended usage pattern.  Create wants you to work inside the closure for a few reasons:

1. it clearly separates producing from consuming.  The function passed to create is responsible for producing events.  Code outside that function should only consume them.
2. it can help to manage resources, so you don't make mistakes that leak resources. Create will use the producer and disposer function (returned by the producer) to start/stop the production of events automatically as new observers are added and removed.

I see you've isolated that in [subject.js](https://github.com/TylorS/cycle-more/blob/master/src/subject.js), which is probably the best way to do it, if you need externalized imperative push semantics.

**Comment by wishfoundry** [comment]
I needed to reimplement rx's ReplaySubject as well, you can borrow some ideas from mine in [this gist] (https://gist.github.com/wishfoundry/ffe4f61c7acd276371d7), which can replay more than just the last event.

@TylorS looking at your subject.js, are you sure you can use setImmediate? I suspect that it may drop events as push really must be in another stack frame when called. Also, you may want put in a call to stream.drain() before returning the stream as by definition, Subjects must be "hot".

**Comment by TylorS** [comment]
Awesome @wishfoundry! I suppose that my implementation is much more naive, yours is obviously much more like the real thing.

**Comment by Frikki** [comment]
@TylorS Also, `setImmediate( fn )` is imperative and not in line with functional programming. You’d probably choose a word like `now( fn )`.

**Comment by TylorS** [comment]
For anyone else looking for this, I have an implementation here https://github.com/TylorS/most-subject.
In combination with https://github.com/mostjs/hold a ReplaySubject-like stream can be created though only with 1 past value, as that's the common use case.

@briancavalier Do you think it is safe to close this?

**Comment by briancavalier** [comment]
@TylorS Thanks for adding the link to your `most-subject`!  Yeah, I think we can close this.
