### ISSUE TITLE
scan fails to emit seed value immediately

### ISSUE THREAD

**Issue by axefrog** [cujojs/most#175]
As I understand it, the default/seed value provided to `scan` should be emitted immediately upon consuming the stream. Instead, it appears to be waiting for the first received item before emitting anything, which means nothing is emitted to begin with, and when an item of data is eventually received, the seed value is then emitted, immediately followed by the first transformed data item.

**Comment by briancavalier** [comment]
Thanks @axefrog.  I should have time to look into this later this week.
