### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by oskbor** [cujojs/most#181]
Hello there!
I couldn't find any typescript definitions for this package. Do you know if there are some available somewhere? Is this something you could consider adding?
best regards Oskar

**Comment by briancavalier** [comment]
Hi @oskbor.  Afaik, there's no TS definition available currently.  It'd be great to have help from the TS community in contributing TS defs for most.  Any chance you'd like to help with that, or perhaps know someone who could?

**Comment by oskbor** [comment]
I would love to help but I haven't used typescript at all, just planning to try it out together with most.js. If I find someone who can help, or if I decide to try my hand at this, I will update here.

**Comment by briancavalier** [comment]
@oskbor This is being tracked in #186.  I'll close this issue, and we can move discussion over to that PR.
