### ISSUE TITLE
seamless switch

### ISSUE THREAD

**Issue by maxhoffmann** [cujojs/most#192]
Has anyone considered adding [`flatMapLatest`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplatest.md) to `most`?

This is the problem I try to solve:
For each url I get from a stream, create a new EventSource connection. Whenever a new url is emitted I need to create a new connection and close the old one as soon as the first event of the new connection arrives.

`flatMap` leaves each connection open, as it does not unsubscribe from old streams. Another popular use case for `flatMapLatest` is autocomplete while typing. Users only care about suggestions for the currently entered text, previous requests can be discarded.

Maybe I’m missing something and this can be easily achieved with the current combinators?

**Comment by TylorS** [comment]
@maxhoffmann 
```js
stream.map(someFunctionThatReturnsAStream).switch()
```
Is the equivalent of `flatMapLatest()`

**Comment by maxhoffmann** [comment]
Wow that was quick. Thanks!

I tried it and it closes the previous stream as soon as the new one is created. Do you have an idea how I could delay switching over to the new stream until the first event of it has arrived?

**Comment by TylorS** [comment]
@maxhoffmann That's not actually what Rx's `flatMapLatest()` does either, it operates exactly the same way `.map().switch()` does in most. 

This **could** be a possible solution, but it has a caveat
```js
const pairwise = (initial, stream) => stream.loop(withPrev, initial);
const withPrev = (prev, x) => ({ seed: x, value: [prev, x] });

pairwise(someInitialValue, stream.map(functionThatReturnsAStream))
  .map(([prev, curr])) => prev.takeUntil(curr).concat(curr)).switch()
```

@staltz pointed out this
> takeUntil subscribes to curr, so you’d have both prev and curr subscribed
Then when the first curr event happens, you unsubscribe from both curr and prev, THEN you make a new subscription to curr, which starts curr all over again if it’s cold

So depending on your use-case this could work, but if the streams in question are 'cold' you may run into unexpected behavior. If you could explain your use-case further we may be able to help more, but if you *are* in fact dealing with 'cold' streams this could possibly require a new operator entirely.

**Comment by briancavalier** [comment]
Hey @maxhoffmann, this "wait until first event on the newly switched-to stream" is definitely an interesting situation.  Have you implemented it successfully using another library (rxjs?).

**Comment by maxhoffmann** [comment]
Thanks for the code snippet @TylorS. Unfortunately in my use case the streams are cold.

@briancavalier I haven’t found a solution yet. Just came across this problem today.

The specific use case is creating a seamless stream of [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) data that can change EventSources when it receives new URLs without any timeouts between closing/connecting.

```
URLs:         ----url1------url2------------->
EventSource1: ----connect-------4-1-7-3-|
EventSource2: --------------connect---6-2-5-->
Result:      -------------------4-1-7-6-2-5-->
```

The current EventSource should only close after the first event of the new EventSource was emitted, so that a seamless stream of data is guaranteed.

**Comment by briancavalier** [comment]
Ok, got it.  Thanks for clarifying.  My intuition is that it *is* possible, but also very non-obvious right now :)  Let's keep brainstorming on it here and see what we can come up with.

**Comment by briancavalier** [comment]
Here's another strawman.  It seems a little unstable when two events coincide the instant of switching (possibly other cases, too).  There's also *a lot* going on ... using two `join`s is a bit expensive.  The `multicast` is probably necessary to prevent total chaos if `outer` is cold.

In essence, given a stream of streams, `doLazySwitch` maps each inner stream to a version of itself that runs `until` the first event of the next stream to arrive on `outer`.

```js
import { join, take, map, until, multicast } from 'most';

const lazySwitch = outer => doLazySwitch(multicast(outer));

const doLazySwitch = outer => join(map(curriedUntil(join(outer)), outer));
const curriedUntil = outer => inner => until(outer, inner);
```

**Comment by TylorS** [comment]
Whoah O.o

**Comment by maxhoffmann** [comment]
Thanks for help. The problem I face has to be solved on the server for different reasons, but I learned a lot from this. :)

**Comment by briancavalier** [comment]
Cool, glad it was helpful!
