### ISSUE TITLE
flatMapError() does not get called if stream explicitely end()'ed

### ISSUE THREAD

**Issue by rielsi** [cujojs/most#196]
If I `end()` created stream, `flatMapError()` doesn't get triggered:
```
most
    .create((add, end, error) => {
        add()
        end()      // notify subscribers they are free to unsubscribe
    })
    .tap(() => { throw new Error() })
    .flatMapError(err => console.error(err))
    .drain()
```
I do expect it to not swallow error. In the following case the error does get catched, though:
```
most
    .create((add, end, error) => {
        add()
    })
    .take(1)       // signal to subscribers they may unsubscribe
    .tap(() => { throw new Error() })
    .flatMapError(err => console.error(err))
    .drain()
```
However, in the latest case my main consideration is this: do subscribers unsubscribe when `take(x)` stream completely consumed?

**Comment by briancavalier** [comment]
Hi @rielsi, thanks for the examples!  At first glance, it seems like those two should be equivalent, so there may a bug.  I'll look into it more later today.

> do subscribers unsubscribe when take(x) stream completely consumed?

Yes: `const s2 = s1.take(1)` will end immediately after 1 event is delivered (if not earlier, due to s1 being empty, for example).

**Comment by briancavalier** [comment]
@rielsi I found the issue.  There's a timing issue due to some of the async shenanigans that `create` does, and the fact that `create` is multicast by default.

I'll think through a solution.

On a related note, can I ask what your use case for `create` is?

**Comment by rielsi** [comment]
Hi @briancavalier, I use `most.create()` mostly to integrate callbacks into stream:

```
...flatMap(result =>
    most.create((add, end, error) =>
        somebody.do(something, (err, result) =>
            err ? error(err) : (add(result) || end())
        )
    )
)...
```
I also use it in my own Subject implementation (the lightest-weight one which I manage to think of):

```
function subject() {
  const subj = {
    in_: {},
  }
  subj.out = most.create((add, end, err) => {
    subj.add = subj.in_.add = add
    subj.end = subj.in_.end = end
    subj.err = subj.in_.err = err
  })
  subj.out.drain()
  return subj
}
```
which I then use like this:
```
function () {
    const subj = subject()
    somebody.work().then(subj.add)
    return subj.out
}
```

**Comment by briancavalier** [comment]
Thanks for the examples.  `most.create` is intended to be a fallback for cases where you are forced to use an imperative approach.  So, it's almost always best to find another way to build a stream.  There are other operators that can help.  For example, if you have a promise (like in your last example), you can use [`fromPromise`](https://github.com/cujojs/most/blob/master/docs/api.md#mostfrompromise).

If you absolutely need an imperative solution, take a look at @TylorS's [`most-subject`](https://github.com/TylorS/most-subject/blob/master/src/index.js). It's quite nice, and isn't based on `most.create`, so is more efficient, and provides other benefits as well.

I hope that helps.

All of that said, there *is* still a bug here :)  I just haven't had time to look into it yet!

**Comment by rielsi** [comment]
Oh, didn't think [most-subject](https://github.com/TylorS/most-subject/blob/master/src/index.js) may be more efficient than barebones `most.create`, will try it then. Thank you.

**Comment by briancavalier** [comment]
@rielsi `most.create` was deprecated and remove in favor of the new [`@most/create`](https://github.com/mostjs/create) a la carte package.  There were also some fixes to `recoverWith` (the new name for `flatMapError`).  I just retried your original example (with `.take(1)`) using `@most/create` and it works correctly.

So, I'm closing this, but if you encounter it using `@most/create`, please reopen!

Also, did most-subject work for you?
