### ISSUE TITLE
sampleWith breaks when value stream is debounced

### ISSUE THREAD

**Issue by maxhoffmann** [cujojs/most#197]
`sampleWith` stops sampling events in my current project after one of the input streams changes. The stream transformation looks something like this:

```js
const coordinateStream = most.combineArray(
    (gridSize, viewport, center, zoom) => calculateCoordinates({ gridSize, ...viewport, center, zoom })
  , [gridSizeStream, viewportStream, centerStream, zoomStream]);

const brokenStream = most.combine(
    (init, coordinates) => ({ init, coordinates })
  , initStream, coordinateStream)
  .map(transformation1)
  .map(transformation2)
  .sampleWith(most.periodic(1000))
  .skipRepeats();
```

The weird thing is that it works when `centerStream` or `zoomStream` emit events, but it breaks as soon as `viewportStream` does. I’ve tapped into `brokenStream` before and after `sampleWith` to see if it receives new and correct values and it does, but it just stops sampling when `viewportStream` emits a new event. Removing `sampleWith` fixes the problem, but obviously results in a stream that does emit values more than once a second.

The description might be too quite vague, but I’m not sure what other information I can give that is helpful. Any ideas?

**Comment by maxhoffmann** [comment]
Quick update: I think the issue seems to be the combination of `debounce` and `sampleWith`. I compared the `viewportStream` to the other ones and `debounce` was something the others don’t have. This is how it looks like:

```js
const viewportStream = most.fromEvent('resize', window)
  .debounce(200)
  .map(() => document.getElementById('visualisation').getBoundingClientRect())
  .map(convertClientRectToObject);
```

As soon as I remove `debounce` the other stream `brokenStream` still works as expected with `sampleWith`.

**Comment by briancavalier** [comment]
@maxhoffmann Thanks for the info and the update.  If you can whittle it down to a runnable test case, I can dig into it later today.

Note: One thing about debounce (which you probably already know), is that if events *always* occur more frequently than the debounce period (in millis), then it effectively will drop all events after the first one.  Not sure if that's helpful, but figured it was worth mentioning just in case.

**Comment by maxhoffmann** [comment]
@briancavalier Sure, I was able to reproduce a minimal use case: http://requirebin.com/?gist=6216878c8a507a37da0b

```js
var clicks = most.fromEvent('click', document)
  .map(function() { return 'click' })
  .debounce(200)
  .startWith('init')
  .sampleWith(most.periodic(1000));

clicks.forEach(function(value) { document.body.innerHTML += value + '<br>'});
```

At first it works, `init` is printed every second. After the first click `click` is printed every second.
But after the second click the stream stops.

**Comment by TylorS** [comment]
I can confirm that I am experiencing the same behavior.

**Comment by briancavalier** [comment]
Thanks @maxhoffmann for the runnable example, and thanks @TylorS for confirming!

Yep, I was able to reproduce as well.  Looking into it now.

**Comment by briancavalier** [comment]
Found the issue.  There's a very subtle bug in the Scheduler [right here](https://github.com/cujojs/most/blob/master/lib/scheduler/Scheduler.js#L81-L82).  If `findIndex` returns -1 to indicate that the task was *not found*, it'll pass -1 to `splice`, which incorrectly will *remove the last task in the list*.  The fix is to check that the result of `findIndex` is `>= 0`.

I should be able to release a patch version tomorrow.

If you want to try it, you can replace `Scheduler.prototype.cancel` with this:

```js
Scheduler.prototype.cancel = function(task) {
	task.active = false;
	var i = binarySearch(task.time, this._tasks);

	if(i >= 0 && i < this._tasks.length) {
		var at = base.findIndex(task, this._tasks[i].events);
		if(at >= 0) {
			this._tasks[i].events.splice(at, 1);
			this._reschedule();
		}
	}
};
```

**Comment by maxhoffmann** [comment]
Thanks a lot for fixing this so quickly! Will pull the fixed version as soon as it is released. :)

**Comment by briancavalier** [comment]
@maxhoffmann No problem!  [0.18.1 just landed](https://github.com/cujojs/most/releases/tag/0.18.1).  Let me know if it works for you.

**Comment by maxhoffmann** [comment]
@briancavalier updated and works as expected. :+1: thanks!
