### ISSUE TITLE
Better unhandled error reporting

### ISSUE THREAD

**Issue by rielsi** [cujojs/most#198]
In the current implementation of most.js, an error thrown in stream does not get reported, the actions down-stream are silently dropped (unless the stream is protected with `flatMapError` of course):
```
most.of(42)
  .tap(() => { throw new Error() })
  .drain()
  // No sign stream was interrupted!
```
Debugging _silently handled_ errors is a real pain. Yet, planting `flatMapError` before every consumer throughout a program adds a significant amount of noise, and is error-prone by itself. I would rather prefer an unhandled error to crash the program early. More sensible may be to propagate unhandled errors the way [Bluebird](https://github.com/petkaantonov/bluebird/) does it with [Global rejection events ](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events):
```
import Promise from 'bluebird'
Promise.resolve(42).then(() => { throw new Error() })
// "Unhandled rejection Error" -- expected it, no surprises
```

**Comment by TylorS** [comment]
`.drain()`, `.observe()`, `.forEach()`, and `.reduce()` all return Promises so you could do

```js
most.of(42)
  .tap(() => { throw new Error() })
  .drain()
  .catch(err => console.error(err))
```

**Comment by briancavalier** [comment]
@rielsi As @TylorS says, most reports errors through the returned promise.  It uses the global `Promise` constructor, so you can shim that with your promise implementation of choice, including ones with good unhandled rejection reporting, such as `creed`, `when`, and `bluebird`.

For example:

```js
require('creed').shim();
import { just } from '../most';

just(42).tap(oops).drain();

function oops() { throw new Error(); }
```

```
most|master⚡ ⇒ ./node_modules/.bin/babel-node experiments/example
/Users/brian/Projects/cujojs/most/node_modules/creed/dist/creed.js:506
        throw e.value;
        ^

Error
    at oops (example.js:8:25)
    at transform.js:43:3
    at MapSink.event (Map.js:54:21)
    at PropagateTask.emit (core.js:24:7)
    at PropagateTask.run (PropagateTask.js:36:7)
    at ScheduledTask.run (Scheduler.js:18:19)
    at runTask (Scheduler.js:32:15)
    at runTasks (Scheduler.js:159:4)
    at Scheduler._findAndRunTasks (Scheduler.js:148:17)
    at Scheduler._runReadyTasks (Scheduler.js:130:21)
```

**Comment by rielsi** [comment]
@TylorS good catch) but what I strive for is to reduce boilerplate error catching (for the purposes of unhandled exception logging, at least), both at the most.js level _and_ the Promise level...
@briancavalier I see, shimming may be the solution, will try it today. Yet thinking, the "re-throw all unhandled exceptions" may be a profound default in a majority of cases.

**Comment by rielsi** [comment]
Shimming native `Promise` with Bluebird's error handling capability indeed as simple as:
```
import Promise from 'bluebird'
global.Promise = Promise
```
...gives me nice stack traces all over the the console. *Solved.* @briancavalier, may I suggest mention this use case for shimming the `Promise` near [README#Requirements](https://github.com/cujojs/most#requirements)? Please close this issue when you are good with it. Thank you very much.

**Comment by briancavalier** [comment]
> may I suggest mention this use case for shimming the Promise near README#Requirements

Thanks for the suggestion @rielsi!  I [added a note to that section.](https://github.com/cujojs/most/commit/11ff8ba7eb5338a45e992ee5f8aed554bb64c584)
