### ISSUE TITLE
Array iterations are not lazy?

### ISSUE THREAD

**Issue by standy** [cujojs/most#217]
In my app im getting an array of item ids, and then trying to fetch the items.
There simplified example: http://requirebin.com/?gist=65ee1826b0805e595f60
```js
var most = require('most');

getList$()
	.concatMap(getItem$)
	.forEach(x => console.log('got', x, new Date().toISOString()));

// helpers
function getList$() {
	return most.from([1,2,3,4,5]);
}
function getItem$(id) {
	return most.fromPromise(fakeFetch(id))
		.map(id => 'item:' + id);
}
function fakeFetch(value) {
	console.log('fetch', value);
	return new Promise(resolve => setTimeout(resolve, 1000, value));
}
```

To my wonder all fetch starts right away:
```
fetch 1 (0s)
fetch 2 (0s)
fetch 3 (0s)
fetch 4 (0s)
fetch 5 (0s)
got item:1 (1s)
got item:2 (1s)
got item:3 (1s)
got item:4 (1s)
got item:5 (1s)
```

But i need like that:
```
fetch 1 (0s)
got item:1 (1s)
fetch 2 (1s)
got item:2 (2s)
```

The only workaround i found is to wrap my fetch to another concatMap + most.just
```
getList$()
	.concatMap(id => most.just(id)
		.concatMap(getItem$)
	)
```

This is not an issue, but more a question:
Is there way to make it simpler? Because double concatMap not seems right

**Comment by briancavalier** [comment]
Hi @standy.  Great question.  Most is lazy at the event stream level, but not at the level of the items within the stream.  That is, event streams are inert until observed, but once observed, eagerly evaluate their events.  In your example, the stream created from an array will eagerly produce all of the numbers from the array, and `concatMap` will eagerly call `getItem$` on each number.

You've raised a good point about `concatMap`.  It would be very easy to change it to map items lazily.  I figure some people would find it unintuitive.  On the other hand, you found it unintuitive that `concatMap` *doesn't* map lazily :)  So, I think I'd like to experiment with that idea.  I'll create a PR (or if you'd like to take a shot at it, let me know!) sometime this week so folks can play with it in a branch, and we can see if there are any performance impacts (good or bad).

In the meantime, you could reduce the array using `continueWith`, which is effectively a lazy concat.  Off the top of my head:

```js
import { empty, from, fromPromise } from 'most'

const lazyConcat = (s, x) =>
  s.continueWith(() => getItem$(x))

const stream = [1, 2, 3, 4, 5].reduce(lazyConcat, empty())

stream.forEach(x => console.log('got', x, new Date().toISOString()))
```

**Comment by briancavalier** [comment]
@standy See #218.  Feel free to give it a try.  Would be interested to hear your thoughts!

**Comment by briancavalier** [comment]
Closing since #218 has been merged.
