### ISSUE TITLE
fromEvent on event with more than one argument

### ISSUE THREAD

**Issue by jfedyczak** [cujojs/most#225]
Is it possible to use `most.fromEvent` on events with more than one argument? For example node's `http.createServer()` emits events with arguments `req` and `res`. I tried passing mapping function as third argument to `fromEvent` but it didn't work.

UPDATE: After reading the source code, I found out that in this case Stream emits an array of arguments. This makes this issue documentation related :)

**Comment by briancavalier** [comment]
> This makes this issue documentation related

Ah, you're right, @jfedyczak.  Thanks for pointing this out.  We should add info about it in the API docs.  Would you be up for submitting a PR?

**Comment by jfedyczak** [comment]
I've created [PR](https://github.com/cujojs/most/pull/226).

**Comment by jfedyczak** [comment]
PR has been merged, so I'm closing this one. Thanks.
