### ISSUE TITLE
Failed 'npm install most'

### ISSUE THREAD

**Issue by syarul** [cujojs/most#241]
I'll get this error

```npm ERR! 404 'most/multicast' is not in the npm registry.```

**Comment by briancavalier** [comment]
Hey @syarul, most uses [scoped packages](https://docs.npmjs.com/getting-started/scoped-packages).  Are you using a version of npm that supports scoped packages?

<img width="833" alt="screen shot 2016-04-26 at 9 41 07 pm" src="https://cloud.githubusercontent.com/assets/90518/14839287/a6475a22-0bf7-11e6-86eb-9e366d013416.png">

**Comment by syarul** [comment]
Ok, sure thing, I'll try that. Thanks for the super fast reply

**Comment by briancavalier** [comment]
No problem!
