### ISSUE TITLE
multicast+combine "i must be >= 0" error

### ISSUE THREAD

**Issue by milankinen** [cujojs/most#247]
Hi,

I encountered a strange error message while testing most's multicasting performance. Here is my code:
```js
const most = require("most")

const arr = [1, 2, 3, 4];

const m1 = most.just(most.from(arr)).delay(1).switch().multicast();
const m2 = m1.map(x => x + 1);
const m3 = m1.map(x => x + 2);
const m4 = m1.map(x => x + 3);

most.combineArray(addAll, [m1, m2, m3, m4])
  .filter(even)
  .drain()
  .then(
    () => console.log("done"),
    err => console.error("error", err)
  )
  

function even(x) { 
  return x % 2 === 0;
}

function addAll(a, b, c, d) {
  return a + b + c + d;
}
```

When I try to run that example, I get an error message `[TypeError: i must be >= 0]`. If I remove the `.multicast()` statement, everything works fine. Any ideas what could cause that error message?

**Comment by briancavalier** [comment]
Hey @milankinen, thanks!  This looks like a bug in `@most/multicast`.  I opened https://github.com/mostjs/multicast/issues/11 to track it.
