### ISSUE TITLE
Race condition in multicast + concat

### ISSUE THREAD

**Issue by dypsilon** [cujojs/most#257]
Sorry for an issue without test code, please feel free to close it if you can't reproduce, but I don't have time to reconstruct a race condition right now. I hope the description will provide enough guidance to fix the issue.

**Steps to reproduce**:
1. Create stream A with multicast().
2. Create stream B from stream A and start observing.
3. Concat stream A to stream Z (Z.concat(A)), resulting in stream C.
4. Start observing stream C.

**Expected**:
All events from stream Z arrive first, then events from stream A. Every time. 

~~~
Stream A: -a1-a2-a3-a4->
Stream B: -a1-a2-a3-a4->
Stream C: -z1-z2-z3-a1-a2-a3-a4->
Stream Z: -z1-z2-z3|
~~~

**Actual**:
Some events at the beginning of stream A are skipped _sometimes_. The sometimes part hints at a race condition. At other times everything works as expected.

~~~
Stream A: -a1-a2-a3-a4-a5->
Stream B: -a1-a2-a3-a4-a5->
Stream C: -z1-z2-z3-a4-a5->
Stream Z: -z1-z2-z3|
~~~

**Hints**
Sometimes C looks as expected. At other times events from stream A are _replaced_ with events from stream Z.

**Comment by briancavalier** [comment]
Hey @dypsilon.  This sounds like the classic "hot vs. cold" issue rather than a race condition (most doesn't exactly have the "hot" and "cold" distinction like RxJS does, but there are similarities).  Could it be that the behavior you see correlates to the kind of source used to create A?  For example, do you always see one behavior when A is "cold", e.g. `from(array)`, and always see the other behavior when A is "hot", e.g. `periodic` or `fromEvent`?

**Comment by dypsilon** [comment]
Hi @briancavalier, thanks for the fast response. I see both behaviors when I run the same code multiple times. So I just restart the script multiple times and sometimes everything is all right. So A is always hot, the events are pushed using a publisher function.

I did a rewrite without multicasting and everything works as expected. So now I just create two different streams with the same events from the beginning and concat works as expected on the second one without failure.

I'm using **0.19.3** which is published on npm right now, not the master.

**Comment by briancavalier** [comment]
Hmmm, ok, interesting.  If you can post a test case when you have time, that'd be great.  Thanks!

**Comment by dypsilon** [comment]
I'm still having problems even after removing multicast. Maybe the problem is really in the source.

**Comment by dypsilon** [comment]
I have found a workaround in my program for now, the issue seems to be with the unreliable source, though I'm still not sure.

**Comment by briancavalier** [comment]
@dypsilon Ok, feel free to reopen if it turns out to be a most.js bug!
