### ISSUE TITLE
Most not reporting error when using most.create.

### ISSUE THREAD

**Issue by p2004a** [cujojs/most#258]
I started using most today and stumbled on the problem with most not reporting any errors when there is `end` function call right after `add` function call in `most.create`. Here is minimal code presenting the behaviour:

```javascript
const most = require('most');

most.create((add, end, err) => {
    add('dummy element');
    end();
})
    .map(e => {
        throw new Error('This should be reported');
    })
    .drain()
    .catch(err => console.error(err.message));
```

This code doesn't print "This should be reported" string as I expected. After commenting `end` call it prints the string.

I'm using node v6.1.0 and most 0.19.3.

**Comment by briancavalier** [comment]
Hey @p2004a, thanks for reporting this, and for including a test case!  I just pushed a potential fix to the [isolate-deferred-sink-errors branch](https://github.com/cujojs/most/tree/isolate-deferred-sink-errors).  Could you try that and see if it works for you?

If so, I'll clean up that branch and get it into a PR asap.

**Comment by p2004a** [comment]
Hi @briancavalier thanks for quick reply. Yeah, I tested your patch and it solved this particular issue BUT this code:

```javascript
const most = require('most');

most.from([1,2,3])
    .chain(e => {
        throw new Error('This should be reported');
    })
    .drain()
    .catch(err => console.error(err.message));
```

Doesn't work as expected. I'm not sure if it is same issue or a different one.

**Comment by briancavalier** [comment]
> I tested your patch and it solved this particular issue

Great, I'll get that ready for PR soon.

>  I'm not sure if it is same issue or a different one.

Hi @p2004a, thanks again for the example.  Yes, it's a different issue--could you open a separate github issue for it?  Thanks!  I'll work on getting PRs ready for that one as well.

**Comment by p2004a** [comment]
Ok, thank you. Done.

**Comment by briancavalier** [comment]
See #261
