### ISSUE TITLE
Remove lodash and Array from perf tests

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#263]
See #243

> After much thought and discussion, we've decided that we should remove lodash and Array from the perf test suite. The main reason is that they fulfill very different use cases. They're interesting points of reference, but including them can give the wrong impression: that most, rxjs, etc. should be used for synchronous collection processing.

> Removing them gives a more apples-to-apples comparison, which is probably more helpful to reactive users.

**Comment by jadbox** [comment]
Kinda wish we left them in.. for academic purposes
