### ISSUE TITLE
Maximum call size exceeded in forEach

### ISSUE THREAD

**Issue by maxhoffmann** [cujojs/most#272]
Hey @briancavalier!

I just stumbled across an interesting problem with most. I get a call size exceeded error pushing a big array into a different one inside of `forEach`.

Example:
```js
const destinationArray = [];

stream.forEach(bigArray =>
  destinationArray.push.apply(destinationArray, bigArray)
);
```

The error is thrown at the line where `push` is happening. `bigArray` has a size of ~170k items. Removing the call, does not throw the error.

Cheers!

**Comment by maxhoffmann** [comment]
I’ve created a requirebin: http://requirebin.com/?gist=6cbb9322be8891d5cb04845bb375f671

**Comment by campersau** [comment]
I don't think this has something to do with most.js. See http://stackoverflow.com/questions/22123769/rangeerror-maximum-call-stack-size-exceeded-why

Using a normal `for` loop in your code fixed this:
```js
for (var value of bigArray) {
  dest.push(value);
}
```

**Comment by briancavalier** [comment]
@maxhoffmann this is a general JS issue, as @campersau pointed out: `apply` spreads the array onto `push's` argument list.  So, you get a call to push that looks like `push(bigArray[0], bigArray[1], ... bigArray[169999])` ... iow, an argument list of 170k parameters!  [JavaScript in general can't handle that](http://stackoverflow.com/questions/22123769/rangeerror-maximum-call-stack-size-exceeded-why).

You could use `concat` instead, or roll your own simple helper that uses a loop as @campersau suggested.

Closing, but please reopen if you suspect there's more to it.  Cheers!

**Comment by maxhoffmann** [comment]
Oh sorry, did not know the list of arguments can exceed the call stack in JS as well. Learned something new. Thanks for answering!

**Comment by briancavalier** [comment]
No worries.  It's kind of a crazy and unhelpful error message :(
