### ISSUE TITLE
Observable functions?

### ISSUE THREAD

**Issue by evilsoft** [cujojs/most#283]
Is there any reason to not allow observable function to be used with `most.from`?

From what I read from the spec, I cannot find where the Observable has to be an object. Just that it needs to implement the Observer interface. Being able to observe a function would clear up a lot of boiler plate when working with virtual-DOM implementations that allow state changes on some app state to re-render when that state has been changed.

Yes I know this is very imperative in practice, but by allowing it, the imperative bits could be squirreled away in a lib and allow state changes by making an `update` observable function.

Thinking something like this, please do not mind the nasty mutations and what not, just something to throw together for this issue. Also error handling and making sure we were passed an obserserver are not implemented here:

```javascript
function observeFunc(f) {
  const subs = []
  const done = false

  function subscribe(o) {
    if(subs.indexOf(o) === -1) {
      subs.push(o)
    }

    return {
      closed: () => done,
      unsubscribe() {
        const idx = subs.indexOf(o)
        if(idx !== -1) { subs.splice(idx, 1) }
      }
    }
  }

  function BigBoy(x) {
    const y = f(x)
    subs.forEach(s => s.next(y))
  }

  BigBoy[Symbol.observable] = () => {
    return { subscribe }
  } 

  return BigBoy
}

const x  = observeFunc(x => x)
const x$ = most.from(x)

x$.observe(console.log.bind(console, 'observed x: '))

x(2)
x(10)
```

so if `x` was an updater function we use it as eventHandlers that dispatch the new state through the stream.

This could be accomplished by changing this line: https://github.com/cujojs/most/blob/master/lib/observable/getObservable.js#L11

from:
```javascript
if(o != null && typeof o === 'object')
```

to:
```javascript
if(o != null && (typeof o === 'object' || typeof o === 'function'))
```

If you have no objections to this, I can get over my feelz about tab indentation and the use of semi-colons :stuck_out_tongue_winking_eye:  and submit a PR with this change and update specs.

***Edit*** Forgot to add the ability to pass the observer function in. :anguished: and name to something a bit more appropriate.

**Comment by briancavalier** [comment]
Hey @evilsoft.  Yeah, you're right, I don't see anywhere it specifically disallows a function.  In fact, getObservable is probably being overly strict in both `typeof` checks.  [This code in es-observable](https://github.com/zenparsing/es-observable/blob/master/src/Observable.js#L313-L329) appears to allow the thing with a method at Symbol.observable to be anything `!= null`, and the thing returned by that method to be an object, array, or function (anything for which `Object(x) === x`).

Would you be up for sending a PR to make `getObservable` match that behavior?

Though we may want to see what feedback you get on https://github.com/zenparsing/es-observable/issues/100 first.

**Comment by evilsoft** [comment]
:+1: I will totes wait for that feedback. would be silly if it is not something that will be a thing in the spec, to implement it. Already started jic :wink:, will push up if they say yay!

I hope they dig, I just started writing a small lib that will wrap a function in an observable up for you.

**Comment by evilsoft** [comment]
Although I cannot find a contrib guide here. Am I missing something? Or is it just make sure it lints and set up the editor with `.editorconfig`?

**Comment by evilsoft** [comment]
Looks like it is cool, any object can be used. Gonna get this going, will PR.

**Comment by evilsoft** [comment]
Merged related PR. closing this out.
