### ISSUE TITLE
support for EventListenerOptions

### ISSUE THREAD

**Issue by marcog83** [cujojs/most#288]
Hi, 
is there support for EventListenerOptions?
I mean that chrome started support passive event listener and in order to use it, I need to pass an Object as 3° parameter in most.fromEvent method.

es
```javascript
most.fromEvent("click",button,{passive:true,capture:false})
```

https://github.com/WICG/EventListenerOptions
https://developers.google.com/web/updates/2016/06/passive-event-listeners?hl=en

thanks a lot for this great library

**Comment by briancavalier** [comment]
Hey @marcog83.  It looks like we could easily support it with a tiny change.  `fromEvent` currently [casts it's third argument to a boolean](https://github.com/cujojs/most/blob/master/lib/source/fromEvent.js#L24).  It could just pass it through without the cast, and that would likely work.

Would you be up for submitting a PR?

**Comment by briancavalier** [comment]
Also, it looks like [`@most/dom-event`](https://github.com/mostjs/dom-event) may already "support" it (iow, doesn't cast).  It's a nicer way (imho) to work with DOM events, too :) If you give that a try, let me know if it works for you.

**Comment by marcog83** [comment]
great! It works for my purpose

**Comment by briancavalier** [comment]
@marcog83 For good measure, #290 tweaks fromEvent to allow EventListenerOptions as well :)
