### ISSUE TITLE
API change in `symbol-observable` package

### ISSUE THREAD

**Issue by evilsoft** [cujojs/most#293]
## Breakage to the Max

So when the `symbol-observable` package went to 1.x, it was babel-ified and as such, any common JS reference needs to pull from default name space here:
* https://github.com/cujojs/most/blob/master/lib/observable/getObservable.js#L5
* https://github.com/cujojs/most/blob/e96e111b2ce8ea74328eb1f10f5dfdf45aeb91ab/most.js#L10
* https://github.com/cujojs/most/blob/5cdd679ef1ff37498363cfe5f2f895aea3eed571/test/most-test.js#L5
* https://github.com/cujojs/most/blob/93bc203f0f6413a857020c2f2e3d15ffc73e8b03/test/observable/getObservable-test.js#L4

Just needs to be:
```javascript
var symbolObservable = require('symbol-observable').default;
```

Although I am curious why the spec is not failing. Makes me question the validity of that test. 

*some time later...*
The reason they pass is because symbolObservable becomes: `{ '[object Object]': [Function] }`. So that is now valid according to the spec as it associates `Symbol.observable` to be the string `[object Object]`.

I could fix this up as it is simple enough for my meek mind to understand and throw together some valid specs if ya want.

**Comment by briancavalier** [comment]
Wow.  Nice find, @evilsoft.  Yeah, the problem is that both the tests and the src modules `require` it in the same way, so they both end up seeing the same (incorrect) string.

If I port the test to ES6 and use `import`, the test breaks.  PR coming ...

**Comment by evilsoft** [comment]
I am thinking maybe a spec or two against that symbol lib itself, would keep your tests all sames

**Comment by briancavalier** [comment]
Are you thinking something like asserting that importing and requiring it yield the same thing?  Or did you have something else in mind?

**Comment by evilsoft** [comment]
I sometimes write specs around dependencies that I use, just to see where apis break. I was suggesting just checking the api it provides. But your solution captured the error, which is what is important. And with put writing specs around dependencies.

**Comment by evilsoft** [comment]
Usually only for utilities. like functions from ramda, or little one off polyfills. 
It captures exactly where I touch my deps in the specs and also will catch most errors from major upgrades. But that would be so much extra code for a project like this.

**Comment by briancavalier** [comment]
Cool, yeah, I can see that.  What's funny is that `symbol-observable` is most's only real 3rd party (runtime) dependency ... and it caused a breakage!
