### ISSUE TITLE
pausable/resumeable streams

### ISSUE THREAD

**Issue by skjorrface** [cujojs/most#299]
Hi! Thank you for this wonderful reactive library! I might have missed an operator in the docs but how do I rx-like pause/resume a stream with most.js? Thanks.

**Comment by briancavalier** [comment]
Hey @skjorrface, thanks!  Could you describe your use case, and what you are trying to achieve at a higher level than pause/resume?  Rather than duplicating functionality of another library, we like to consider use cases and solutions on their own first--sometimes that means we end up duplicating functionality of another library, and sometimes not.

Thanks for any additional info!

**Comment by skjorrface** [comment]
I'm completely new to reactive programming so I was trying to create a simple "videogame" using svg.js and reactive libraries to manage time and user interaction with the shapes displayed in the game. Suppose a match has a limited time play of 30 seconds and the player has the ability to pause the match and resume it in a second moment without the "timer" being reset. I learned how to do this with CycleJs + xstream/RxJS and now I was trying with your awesome library. I hope this doesn't sound crazy. Thanks!

**Comment by brandonpayton** [comment]
Hi @skjorrface, one way you could do this is to filter on a `paused` flag.

I've used something like this in the past:
```javascript
var gameStateStream = frameStateStream.scan(
  (gameState, frameState) => { ... },
  initialGameState
)
```

To support pausing, you might do something like this:
```javascript
var gameStateStream = frameStateStream
  .filter(frameState => !frameState.paused)
  .scan(
    (gameState, frameState) => { ... },
    initialGameState
  )
```

I hope this helps.

**Comment by briancavalier** [comment]
Cool, thanks for the additional info @skjorrface!

And thanks, @brandonpayton, for the suggestion.  I like that direction.  I was thinking something similar: an operator that allows a `Stream boolean` to control another stream, i.e. like a toggle:

```js
const pausable = toggle(streamOfBoolean, streamOfEvents)
```

So, pausable would propagate all events when the most recently seen event in `streamOfBoolean` was true, and would drop all events when the most recently seen event in `streamOfBoolean` was false.  IOW, the stream of boolean acts like a controller for pause/upause or drop/allow.

It could probably be implemented with `@most/sample` pretty easily.  Maybe something like:

```js
import { sample } from '@most/sample'

// Partially apply sample
const withToggler = sample((allow, event) => ({ allow, event }))

// Use it to create new toggle() operator
const toggle = (toggler, stream) =>
  withToggler(toggler, stream)
    .filter(({ allow }) => allow)
    .map(({ event }) => event)

// Call it like this:
const streamOfBool = ... // the "controller"
const streamOfEvents = ...

const pausable = toggle(streamOfBool, streamOfEvents)
```

I probably didn't get that exactly right, but I think it's close.

@skjorrface Would the general idea of filtering based on some condition (whether using a `scan`, or something like `toggle`) work for you?

**Comment by skjorrface** [comment]
Thanks guys, that's exactly what I was looking for. This took some time for me to make it work but now I can fully switch to most.js =) Thanks again.

**Comment by briancavalier** [comment]
@skjorrface Great!  Glad we could help.
