### ISSUE TITLE
Help me confirm the library we need

### ISSUE THREAD

**Issue by kennynaoh** [cujojs/most#302]
Hello @briancavalier ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I want to confirm the libraries we need.
According to the `most.js` on [npm](https://www.npmjs.com/package/most), I add three parts.
`lib/source/core.js|from.js|periodic|fromEvent.js|unfold.js|iterate.js|generate.js`
`lib/combinator/*`
`lib/observable/subscribe.js`
Please help me confirm that Whether all of them we need.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8143
https://github.com/cdnjs/cdnjs/pull/8149

**Comment by briancavalier** [comment]
Hey @kennynaoh, sorry for the lack of response here.  Based on https://github.com/cdnjs/cdnjs/pull/8149, it looks like [most is available on cdnjs](https://cdnjs.com/libraries/most).  If there's anything else you need, please let me know.  Thanks!
