### ISSUE TITLE
The new Apply spec for Fantasy-Land

### ISSUE THREAD

**Issue by evilsoft** [cujojs/most#331]
## Most-ly a question
![](http://i.giphy.com/3oEduSWKqDzdWH3W00.gif)
So it looks like there was a big update to the Apply spec [here](https://github.com/fantasyland/fantasy-land#apply).

Basically it reversed the "parameters". So given that `a` is an Apply wrapping a value and `b` is an Apply wrapping a function, it is defined as: `a.ap(b)`

It used to be that `a` wrapped the function and `b` was the value, allowing for "chaining" your Application.

Are there plans to implement against the new spec, or is `most` going to stay locked down to the old spec. I was planning on writing a lib that did some interop with `most` through the fl-interface and am wondering what the plan is.

This of course would mean that now for `ap` you would apply functions to a streamOfValues, instead of applying a values to a streamOfFunctions.

**Comment by briancavalier** [comment]
Hey @evilsoft, thanks for bringing this up.  It seems like the right thing is to rely on semantic versioning: most 1.x can continue to support Fantasy-Land 0.x, and we'll need to release most 2.0 to support the breaking changes in FL 1.0.

I can't really speak to a timeline for most 2.0 yet, but I don't mind being pragmatic about it: if there are important changes that are needed for ecosystem compatibility, then we can consider doing it.

Does that seem reasonable for your project?

**Comment by evilsoft** [comment]
Sounds perfect. Just needed to know what it is you are doing. So I can follow you. 

So happy you honor semantic!! 🎈 🍰 🎈

**Comment by evilsoft** [comment]
Closing this out!!

**Comment by briancavalier** [comment]
Cool.  We're hoping to post a 2.0 roadmap pretty soon.  Fantasy-land 1.0 compat will def be on it.
