### ISSUE TITLE
mergeConcurrently documentation

### ISSUE THREAD

**Issue by Sinewyk** [cujojs/most#335]
Do I misunderstand how the operator works or shouldn't the documentation schema rather show
```
s:                           --a--b--c--d--e-->
t:                           --x------y|
u:                           -1--2--3--4--5--6>
stream:                      -s--t--u--------->
stream.mergeConcurrently(2): --a--b--cy4d-5e-6>
```

If it merges it should push the `b` and `c` events to the resulting stream no ?

edit: [ref](https://github.com/cujojs/most/blob/ad23ff4114742fcddf5b63c26d1212f3cf847f34/docs/api.md#mergeconcurrently)

**Comment by briancavalier** [comment]
Thanks @Sinewyk, that certainly looks like a typo!  Would you like to submit a PR?

**Comment by Sinewyk** [comment]
Yeah sure, there you go https://github.com/cujojs/most/pull/336
