### ISSUE TITLE
Simulating behavior/property with most subjects

### ISSUE THREAD

**Issue by brucou** [cujojs/most#353]
I have been using most subjects for a little while now and I have not been able to use it to properly implement a behaviour (from the dichotomy behavior/event where an event is short-lived and a behavior is continous in time, I think some other people calls that the age/birthday dichotomy).

A hold subject replaying the last value emitted works most of the time, except for the following edge cases:
1. no initial value
2. when the (hold) subject completes, no more value is emitted on subscriptions which happen after that completion

While the first edge case can be worked around in most cases, the second is more problematic. The sought semantic for the hold subject would be to replay the latest value, even after completion. The behavior still has a current value (always has one), the fact that the stream completes just means it won't have any new value (i.e. `next` calls will be ignored). Or is there another/better way to implement behaviors with the current most?

**Comment by TylorS** [comment]
Hey @brucou a new version of `most-subject` has been released. I don't think number 2 is a problem any longer. http://www.webpackbin.com/VJDTGF2xf

**Comment by brucou** [comment]
Looks amazing. Is there a way to modify the webpackbin? Wanted to replace 2 by 1 but I suppose it will work the same.

**Comment by TylorS** [comment]
You should be able to modify it yourself

**Comment by brucou** [comment]
webpackbin apparently does not allow modification in some strange circumstances (screen resolution??), but anyways, I was able to test it in my environment and it seems that the new version of subject (5.0.0+) solves edge cases 2. 
I am subsequently closing this. Thanks for the help.

**Comment by briancavalier** [comment]
Glad to hear most-subject is working for you.
