### ISSUE TITLE
double multicast causes skipping first event

### ISSUE THREAD

**Issue by maxhoffmann** [cujojs/most#359]
Hey @briancavalier!

<details>
 <summary>My old vague bug report:</summary>
 I’ve been chasing down a problem in our app, that seems to be an issue with `multicast`. I’m having a hard time reducing it down to a minimal case and thought I could give you at least a hint, that something is not working as it should.

The bug I see is that adding `multicast` to a stream subscribed by multiple consumers results in the source stream **not emitting the first initial** event for some of them. This leads to our app not initialising correctly. Removing `multicast` fixes the issue, but since it has multiple consumers it should use it, but not break.
 
I’ve tried replacing the producer with `just` and the issue still occurred. The minimal case I could nail it down to for now is having three consumers where the last one is not receiving the initial event. The one not receiving the event is a combination of `combine` and `startWith`. Removing `startWith` fixes the bug.
Removing one of the other two streams or adding another consumer fixes the bug as well. One of them samples the producer and some other streams. Removing a stream there also fixes the bug.

As you can see it’s hard to find the root cause, since it feels quite arbitrary what causes the issue.

Maybe you already have any idea what the problem might be. I’ll keep trying to reproduce it to a minimal example.
</details>

---

**Update:** I could boil it down to a minimum:

```js
const most = require('most');

const producer = most.just().multicast();

const working = most.combine(() => 0, producer).multicast();
const broken = most.combine(() => 2, producer).startWith(1);

working.forEach(value => document.write('working: ' + value + '<br>'));

// expected: brokenConsumer should emit 1 and 2
broken.forEach(value => document.write('broken: ' + value + '<br>'));

// removing one of the multicasts fixes the bug
// removing startWith emits 2
```

**Comment by maxhoffmann** [comment]
I’ve created an ESNextbin too: https://esnextb.in/?gist=4e1952554ddb71f0e70ea4324f5f2cb1

**Comment by axefrog** [comment]
My guess is that this is not a bug but a race condition. Multicast runs the producer and begins emitting to any attached observers the moment the first observer is added. What I suspect is happening your case is that `working` causes the upstream producer to be put into an active state first, resulting in a task being scheduled for the next tick following the producer's activation. The upstream producer schedules its one and only event at that time, which is received by the `working` observer before the `broken` observer has a chance to finish setting itself up. @briancavalier would need to confirm this.

**Comment by TylorS** [comment]
I'm pretty sure what @axefrog has mentioned is correct, to it being a race condition.

This is precisely the kind of use case I've needed [`@most/hold`](https://github.com/mostjs/hold) for.

But to hopefully describe what is happening here, or at least very close to it:

First tick:
  - `producer` is created
  - `working` is created as a descendant of `producer`
  - `broken` is created as a descendant of `producer`
  - `working` is subscribed to
  - `broken` is subscribed to

Second tick:
  - `producer` "broadcasts" the value of undefined to it's listeners. Lets all it "A"
    - A is passed down to `working`s "combine" and then to the `working` forEach
    - A is passed down to `broken`s combine *but*
    - `broken` passes down its `startWith` value of 1 to it's associated forEach.
    
Last tick:
`broken` "continues" its sequence by "switching" to it's associated `combine()` which has already emitted  its events 2 ticks ago, so no value is seen further down the chain.

---

Hope this helps! I wanted to explain why some other ordering/changes will make this work but I need to run. I'll try to add them here if no one else has done so

**Comment by maxhoffmann** [comment]
Interesting, thanks for the description! I don’t understand yet why switching the order of the `.forEach`s does emit both events though. (emits `1 -> 0 -> 2`)

**Comment by axefrog** [comment]
At the risk of coming across as one of those smarmy "RTFM" types, I do suggest reading the architecture wiki page, as it's quite helpful in building an idea of how most works under the hood. I also suggest perusing [some](https://github.com/cujojs/most/blob/master/src/source/core.js#L14-L24) [of](https://github.com/cujojs/most/blob/master/src/combinator/combine.js) [the](https://github.com/cujojs/most/blob/master/src/index.js#L152) [code](https://github.com/mostjs/multicast/blob/master/src/MulticastSource.js); the design has an elegant but powerful simplicity, and once you understand how it works, you'll be able to troubleshoot most problems fairly quickly.

**Comment by maxhoffmann** [comment]
Ok thank, will take a look. 👍 Closing this one then.
