### ISSUE TITLE
TypeError: Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by marvinhagemeister** [cujojs/most#362]
I'm currently in the process of fixing some warnings in some tests of the inferno codebase. [In one particular test case](https://github.com/trueadm/inferno/blob/master/src/DOM/__tests__/functional.spec.tsx#L59) they are using most.js to observe the rendering of components. There `most` throws an unhandled rejection error.

```js
const runApp = () => scan(renderer, container, vNodes$).drain();

runApp(); // Throws an unhandled promise rejection error in node 7.2.0
```

When an attaching an exception handler [stacktrace here](https://gist.github.com/marvinhagemeister/cdcd9a843dd1c9bc378a5a4f2a1ae02c), I get a `TypeError: Cannot read property 'run' of undefined`.

Steps to reproduce:

1. Clone the [inferno repo](https://github.com/trueadm/inferno) (use the master branch)
2. run `npm run build` once
3. it's best to append `.only` to the specified test case, so that mocha skips all the other ones, like `it.only("...` (optional)
4. execute tests via `npm run test:server`

**Comment by TylorS** [comment]
Hello @marvinhagemeister, I think I might have found the problem that you're running into. On [line 26](https://github.com/trueadm/inferno/blob/master/src/DOM/__tests__/functional.spec.tsx#L26) you are incorrectly making use of the latest version of `most-subject`. The line should likely be something like

```typescript
const action$ = hold(1, sync());
```

In v5 `hold()` is a modifier of a subject, not a subject itself. Hope this helps

**Comment by marvinhagemeister** [comment]
Awesome, that was exactly the problem. Thanks for helping out @TylorS 👍

**Comment by TylorS** [comment]
Glad that it was indeed the fix you needed.
Another small suggestion would be that `scan().drain()` === `reduce()` in most :)
