### ISSUE TITLE
can I use it with some polyfill in ie8 ?

### ISSUE THREAD

**Issue by codering** [cujojs/most#363]

**Comment by briancavalier** [comment]
Hi @codering.  Most requires at least an ES5 environment, plus ES2015 Promise.  You can probably find what you need to support IE8 over at [es-shims](https://github.com/es-shims).  I'd guess that either [es6-shim](https://github.com/es-shims/es6-shim#installation) (which already includes a Promise polyfill), or [es5-shim](https://github.com/es-shims/es5-shim) plus a Promise polyfill (like [es6-promise](https://github.com/stefanpenner/es6-promise), [creed](https://github.com/briancavalier/creed), or [bluebird](https://github.com/petkaantonov/bluebird/)) would be a good place to start.

Hope that helps!

**Comment by codering** [comment]
"addEventListener/removeEventListener" may be a problem

**Comment by briancavalier** [comment]
@codering Yeah, if you want to use `most.fromEvent` or [`@most/dom-event`](https://github.com/mostjs/dom-event), you'll need to polyfill `add/removeEventListener`.  I'm sure several exist, and google search would find what you need.

**Comment by davidchase** [comment]
Just as a recommendation for events or other polyfill's we use https://qa.polyfill.io/v2/docs/ its a conditional cdn which only loads the polyfills you want and with the browser that needs them but if you want you could force those polyfills to always load.

For `add/removeEventListener`: https://qa.polyfill.io/v2/docs/features/#Event

**Comment by codering** [comment]
thanks @briancavalier @davidchase
