### ISSUE TITLE
Add support for CancelToken?

### ISSUE THREAD

**Issue by jasonkuhrt** [cujojs/most#365]
Hey,

Its probably too early to begin this in earnest but assuming `most` wants to play well in the spec-compliant world then would it make sense to add support for [`CancelTokens`](https://github.com/tc39/proposal-cancelable-promises) ([detail](https://github.com/tc39/proposal-cancelable-promises/blob/master/Cancel%20Tokens.md)) in any special way?

While `cancelToken.promise` is sufficient to feed combinators like [`until`](https://github.com/cujojs/most/blob/master/docs/api.md#until) I wonder if anything special needs to be done on the error handling side to distinguish between a canceled stream versus a failed one.

**Comment by TylorS** [comment]
I can't speak for the other contributors, but I can say I'm not too interested in becoming spec-compliant. If we were to become spec-compliant, we would almost certainly see a performance drop.

**Comment by ospatil** [comment]
The _cancelToken_ proposal has been withdrawn. More here - https://github.com/tc39/proposal-cancelable-promises/issues/70.

**Comment by briancavalier** [comment]
Thanks @ospatil.

@jasonkuhrt I believe I can safely say that the consensus of the core most.js team has been that we  wouldn't support CancelToken until it had become clear that it would survive and become official.  Now that the proposal has been withdrawn, it doesn't make sense to support it in the core lib.

If someone needs support for it for some reason (CancelToken early adopters??), they can implement an external `subscribe`-like helper that deals with CTs.

**Comment by jasonkuhrt** [comment]
I discovered cancel tokens a mere few weeks ago, and now their out–ha. Sorry for the noise everyone.

**Comment by briancavalier** [comment]
No worries, @jasonkuhrt. Yeah, I think the withdraw was surprising to most folks. I haven't seen a good explanation for the reasons other than "google objected". I wasn't personally a fan of the proposal, but it'd be nice to know the reasons.
