### ISSUE TITLE
Add functional `switchLatest` to API docs

### ISSUE THREAD

**Issue by Frikki** [cujojs/most#374]
Currently, only the fluent style `switch` is mentioned in the API docs. However, because of a native language conflict, `switch` cannot be exported as a functional API, and the provided substitute `switchLatest` has no mention in the API docs.

**Comment by davidchase** [comment]
@Frikki great point! care to send in a PR?

**Comment by Frikki** [comment]
Yes. I’ll do that, @davidchase.

**Comment by Frikki** [comment]
PR #375 sent, @davidchase

**Comment by davidchase** [comment]
sweet thanks so much @Frikki

**Comment by Frikki** [comment]
Tiny, tiny.
