### ISSUE TITLE
shouldn't 'most#from' return a Stream in the error state with 'most#throwError' instead of throwing a synchronous exception?

### ISSUE THREAD

**Issue by smcatala** [cujojs/most#377]
in its current implementation, the `most#from` method throws a `TypeError` when the given argument is not of the expected type.
this requires client code to handle separately the potential _synchronous_ `TypeError` in addition to any _asynchronous_ errors from the Stream, which typically adds overhead code.

wouldn't it be preferable to return a Stream in the error state with `most#throwError` instead of throwing a synchronous error, so that client code can manage all errors asynchronously within the returned Stream?

[Bluebird](http://bluebirdjs.com/docs/api/promise.try.html) offers a `Promise#try` method to wrap code that may throw synchronous exceptions and turn these into rejections, allowing client code to process all errors in `catch` clauses.

**Comment by briancavalier** [comment]
Hi @smcatala.  Good question.  We actually don't want programs to handle that error at runtime.  It's a type-checking error--IOW, the program is invalid.  For example, if you're using TypeScript, most's TS typedefs will cause static type checking to fail.  The closest analog for folks not using a type checker is to fail early and spectacularly in a way that is annoying to handle at runtime.

So, devs should take whatever steps are necessary to ensure that an invalid type is never passed to `from`.

I just realized the exception, and it's meaning, aren't documented in the `from` docs.  Sorry about that.  We should def add it.

**Comment by smcatala** [comment]
ok, got it! thanks for the clarification @briancavalier.

**Comment by briancavalier** [comment]
No problem, @smcatala.  See #385.  Thanks for helping us improve the docs by pointing this out!
