### ISSUE TITLE
Add doc comments to type definitions

### ISSUE THREAD

**Issue by masaeedu** [cujojs/most#388]
The type definitions do not currently have doc comments, which makes it difficult to explore the API or understand what the arguments are supposed to represent. It would be useful if doc comments for the type defs were kept in sync with the actual code.

**Comment by briancavalier** [comment]
@masaeedu Closing, but if you have ideas for how we could achieve this goal without introducing additional maintenance, please do let us know here, or discuss in [gitter](http://gitter.im/cujojs/most).

**Comment by masaeedu** [comment]
@briancavalier I researched this for a bit, but unfortunately I can't think of a way to do this that doesn't involve maintaining two sets of doc comments. Seems like a good case could be made for a TypeScript feature to help out here.

**Comment by briancavalier** [comment]
I appreciate your taking the time to research it.
