### ISSUE TITLE
Is there any method like `most.defer()` and `most.create()`?

### ISSUE THREAD

**Issue by xareelee** [cujojs/most#398]
I did not find `most.defer()` and `most.create()` in the [API docs](https://github.com/cujojs/most/blob/master/docs/api.md).

I need to defer a function call until it is subscribed.

```js
most.defer(() => {
  result = getResult();
  return most.of(result);
})
```

How do I do to achieve my goal?

**Comment by axefrog** [comment]
`create()` is a separate package now, as it's a non-standard use case:
https://github.com/mostjs/create

**Comment by xareelee** [comment]
Ok, thanks.

Is there a package like `@most/defer`? Or should I need to use `most.create()` to send a stream and then `flatten()`?

**Comment by briancavalier** [comment]
Hi @xareelee.  Can you help me understand the use case for a function like defer?  It seems that you'd like create a stream lazily.  All most streams are already lazy, so I'm just guessing that perhaps you'd like to use something like `defer` when initial construction of the stream is somehow expensive?

If that's the case, then it should be fairly simple to make your own.  There are several ways.  Here's one using `continueWith`.  You could do something similar, as you suggested with `just` and `chain`, or `just`, `map` and `switchLatest`.

```js
import { empty, continueWith, just } from 'most'

// Let's make our own defer() function
const defer = f => continueWith(f, empty())

// Use it
defer(() => just(getResult()))
```

Hope that helps. If I haven't understood your question correctly, we'll probably need a bit more detail on what exactly you expect defer() to do.  Thanks!

**Comment by xareelee** [comment]
> Can you help me understand the use case for a function like defer? 

```js
// without `defer`
function foo(options) {
  // has side-effect or inner dependency; would be triggered before the returned stream is subscribed
  const settings = setup_settings(options);
  return most.of(settings);
}

// with `defer`
// we could wrap the whole implementation in the `defer`
function foo(options) {
  // defer the execution until subscribed
  return defer(() => {
    // only be triggered when the this stream is subscribed.
    const settings = setup_settings(options);
    return most.of(settings);
  });
}
```

Using `defer` to keep the impure function to be called only when it is subscribed. It's important if the timing matters.


> ```js
> import { empty, continueWith, just } from 'most'
> 
> // Let's make our own defer() function
> const defer = f => continueWith(f, empty())
> 
> // Use it
> defer(() => just(getResult()))
> ```

I did not try this, but it seems OK if the function `f` passed to the `continueWith()` only be called when subscribed. Thanks for your help.

**Comment by briancavalier** [comment]
> if the function f passed to the continueWith() only be called when subscribed

Yep, that's correct.  Closing since I believe this answers the original question.

Cheers!
