### ISSUE TITLE
How to use `drain` to send the result from a stream

### ISSUE THREAD

**Issue by xareelee** [cujojs/most#402]
I want to turn a Stream into a Promise. When I do this as the following, the result is not expected as I think.

```js
// We create a stream with a value
Most.of({y: 'y', z: 'z'})
  // map it to another one
  .map(data => ({ data, x: 'x' }))
  // Try to print the result before using `drain`
  .tap(next => {
    // got `{ data: { y: 'y', z: 'z' }, x: 'x' }`
    console.log('next:', next)
  })
  // No idea why this is needed. If no `take(1)`, the Promise will get `undefined`.
  .take(1)
  // turn into a Promise
  .drain()
  .then(x => {
    // expect to receive `{ data: { y: 'y', z: 'z' }, x: 'x' }`
    // but got `{y: 'y', z: 'z'}` as unexpected
    console.log('result: ', x);
  });
```

How to turn a Stream into a Promise?

**Comment by davidchase** [comment]
@xareelee thanks for the issue.. if you check out this [webpackbin](http://www.webpackbin.com/Nk_--CkPM)

it seems that the result in the `then` is the one you are expecting, no?

let me know if thats not the case

**Comment by briancavalier** [comment]
@xareelee The purpose of `drain` and `observe` is to consume the events in a stream, and the purpose of the promise they return is only as a signal of completion or failure.

In the case where you'd like to process a stream to a _specific_ value, use [reduce](https://github.com/cujojs/most/blob/master/docs/api.md#reduce).  I apologize that the docs are incomplete, but if you're familiar with reducing an Array, it works in the same way, simply lifted from arrays and values to streams and promises.

In short: reduce is the right combinator for processing a stream and producing a final asynchronous value in the form of a promise.

For example, let's say you wanted to produce a promise for the first event in a stream, ignoring the rest:

```js
import { just } from 'most'

// Technically, take(1) is not needed here since just()
// always contains exactly 1 event, but if you were to switch
// to some other source, like an array, or DOM events, etc.
// you would need the take(1)
just({y: 'y', z: 'z'})
  .take(1)
  .map(data => ({ data, x: 'x' }))
  .reduce((_, x) => x, undefined)
  .then(x => console.log(x)) //> { data: { y: 'y', z: 'z' }, x: 'x' }
```

Or, if you wanted to produce a promise for the first event in a stream, ignoring all the previous events:

```js
import { from } from 'most'

from([{}, {}, {y: 'y', z: 'z'}])
  .map(data => ({ data, x: 'x' }))
  .reduce((_, x) => x, undefined)
  .then(x => console.log(x)) //> { data: { y: 'y', z: 'z' }, x: 'x' }
```

Or, if you wanted to collect all the events into an array, and produce a promise for the final array value:

```js
import { from } from 'most'

from([{}, {}, {y: 'y', z: 'z'}])
  .map(data => ({ data, x: 'x' }))
  .reduce((array, x) => array.concat([x]), [])
  .then(array => console.log(array)) //> [{}, {}, {y: 'y', z: 'z'}]
```

Hope that helps.

**Comment by xareelee** [comment]
@briancavalier Thanks for your help. It works using `reduce`.

I still wonder when and what the cases use `observe` and `drain`.
