### ISSUE TITLE
most.from typing errors

### ISSUE THREAD

**Issue by staltz** [cujojs/most#405]
most.d.ts defines

```typescript
export function from<A>(as: Iterable<A>): Stream<A>;
```

But it's certain (from the JS implementation) that `from` actually supports more types, like array, observable, etc. Currently, TypeScript code that uses most.js will not compile if given e.g. `most.from([10,20,30])`.

**Comment by briancavalier** [comment]
Thanks, @staltz!  Candidate fix in #406
