### ISSUE TITLE
Error handling and most.fromObservable

### ISSUE THREAD

**Issue by Widdershin** [cujojs/most#407]
Hi!

While integrating most with `@cycle/time`, I noticed some curious behavior.

```js
import {Observable} from 'rxjs/Rx';

function boom () {
  throw new Error('boom!');
}

const stream = most.from(Observable.of('a')).map(boom);

stream.subscribe({
  next (ev) {},

  error (err) {
    console.log('Handled error');
  },

  complete () {}
});
```

I would expect this code to log 'Handled error'. Instead the error is thrown when it occurs, not caught and passed into the error handler in subscribe.

If `most.from(Observable.of('a'))` is replaced with `most.of('a')` the code functions as expected.

**Comment by TylorS** [comment]
Thanks for reporting this error @Widdershin 
I've opened a possible solution this problem for others to review in #408
