### ISSUE TITLE
Grouping streams on interval

### ISSUE THREAD

**Issue by geoffreyabdallah** [cujojs/most#409]
Hi!

Great lib, and really looking forward to using it. Our app has what I think is a fairly great use case for streams but I can't seem to wrap my head around how I'd implement it (sorry in advance if this is the wrong forum, but I didn't see a gitter/slack and SO seemed to not have much on mostjs.)

Use case: detect if a user is continuously speaking into their microphone for a certain interval (~1s), if so, send an event off to a socket server that can in turn relay to each client who the active speaker is (think google hangouts.) Ideally, I'd like to use streams so I can eventually join both the volume stream w/ the socket stream to handle both events/logic more gracefully. However, the volume stream is where I'm getting stuck.

Ideally, I'd like a scenario where if a user speaks sometime within 300ms, continuously over a period of 900ms, then I'd register the user as an active speaker. I figure I need something here with a combination of debounces (one at 300ms, and one at 900ms), and a HOS - but again, still having trouble groking on how to go about this.

Bad sample code of what I've attempted:
```
const volume$ = most.create((add, end, err) => {
  // client here is a Twilio client, where volume takes a handler to register input volume at 60 times a second
  client.volume(inputVolume => {
    // 0.15 is around the volume of someone speaking normally - I figured to put the filter here as opposed to putting it on the stream itself
    if (inputVolume > 0.15)  add(inputVolume)
  })
})

/*
and here is where I need to figure out the debounce combos. So if a user speaks at least once for
three continuous intervals of 300ms, then on .observe -> register that said user is active
(this part I'm not concerned about,
just trying to get to the point where .observe would actually be registering said stream.
*/
```

Thanks again for any and all help!

**Comment by briancavalier** [comment]
Hey @geoffreyabdallah, I'm reading this now, but figured I'd quickly point you to the [gitter chat](https://gitter.im/cujojs/most), so you can jump in there for some real time discussion if you'd like.

**Comment by briancavalier** [comment]
Thanks for the description and code sample.  Sounds like you're doing fun things!

My first thought after reading is that I wonder if it's workable to timestamp() every event, and then loop() to accumulate the duration of the time window within which the user has been speaking.  Once that window reaches the desired length, allow an event to propagate.

That may require moving the volume filter out of the `most.create`.

Here's a sketch.  I'm sure it's not exactly what you need, but maybe it will spark more thoughts and discussion :)

```js
const volume = most.create(...)

const speakingWindows = volume
  .timestamp()
  .loop((start, { time, value: inputVolume }) =>
    inputVolume > 0.15
      ? { seed: start, value: time - start } // expand time window
      : { seed: time,  value: 0 } // reset time window
  , 0) // zero as the initial start time isn't right
  .filter(elapsedTime => elapsedTime > 1000)
```

That probably contains way more events than you'd like, and you'd probably want to throttle it or devise some sort of way to only start accumulating again once there is some silence.  Anyway, let's keep discussing here and/or on gitter.

**Comment by geoffreyabdallah** [comment]
Thanks for taking the time to write out a sketch and pointing me towards the gitter! This definitely helps get my thinking in the right direction, and I think is a good jumping off point for me to close this as we continue developing and playing around more with bringing streams into the mix. I'll go ahead and close this issue, and will reference back to this if/when continuing the discussion on gitter.

Thanks again!
