### ISSUE TITLE
Allow additional parameters to thru

### ISSUE THREAD

**Issue by frangio** [cujojs/most#415]
It would be useful to be able to pass additional parameters to `thru`, for use with n-ary stream transformations.
Like `stream1.thru(transform, stream2)` instead of `transform(stream1, stream2)`. It also feels consistent with other parts of the API such as `combine`.

**Comment by frangio** [comment]
The implementation is pretty trivial and I can make a pull request if you're interested.

**Comment by briancavalier** [comment]
Hey, thanks @frangio.  We'd prefer to keep thru as a single arg, and encourage folks to allow multiple args via partial application of the `transform`, which can be achieved easily with `bind` or the currying or partial application helpers from any number of FP libs, like ramda or lodash-fp.

For example, these are equivalent:

```js
// Given an n-arity transform:
const transform = (x, y, z, stream) => // ...

// Via the proposed varargs thru
const stream2 = stream1.thu(transform, x, y, z)
```

```js
// Given a curried transform:
const transform = curry((x, y, z, stream) => /* ... */)

// Via partial application if transform is curried
const stream2 = stream1.thru(transform(x, y, z))
```

We'll add a bit to the docs describing this.
