### ISSUE TITLE
Synchronous code behaves as asynchronous

### ISSUE THREAD

**Issue by Lodin** [cujojs/most#424]
### Summary

I have tried to implement simple functional using `most` + `most-subject`: I have two subjects that maps with simple arithmetic functions and saves into accumulator using `scan`, and a combined stream that presents them as an object.

However, I faced with a strange behavior of this combo. Looks like something works asynchronously. 

### Expected result

I expected to get following messages in console:
```
b1: 0
b: {"b1": 0, "b2": 0}
b1: 150
b: {"b1": 150, "b2": 0}
```

### Actual Result

I have got following: 
```
b1: 150
b1: 0
b: {"b1": 0, "b2": 0}
```
Looks like subscription to a sync subject works well, but something went wrong with combination or scanning.

If I wrap `a1.next` into a zero `setTimeout`, I will get expected results. 
```javascript
setTimeout(() => {
  a1.next(150);
});
```

### Versions

- most.js: 1.2.2
- most-subject: 5.3.0
- node: 6.9.2

### Steps to reproduce

Just execute provided code in any environment

### Code to reproduce

```javascript
const most = require("most")
const subject = require('most-subject');

const a1 = subject.sync();
const a2 = subject.sync();

const b1 = a1
    .map(v => acc => acc + v)
    .scan((acc, handler) => handler(acc), 0);
const b2 = a2
    .map(v => acc => acc - v)
    .scan((acc, handler) => handler(acc), 0);
   
b1.subscribe({
    next: acc => console.log(`b1: ${acc}`)
});

const b = most.combine(
    (b1, b2) => ({
        b1, 
        b2
    }),
    b1, b2
);

b.subscribe({
    next: acc => console.log(`b: ${JSON.stringify(acc)}`)
});

a1.next(150);
```

**Comment by TylorS** [comment]
Hello @Lodin thanks for using most. I hope I can describe what is going on here, in a way that makes sense.

On **first** tick

1. `a1` and `a2` are **created**
2. `b1` and `b2` are **created**
3. A subscriber to `b1` is **registered**
4. `b` is **created**
5. A subscriber to `b` is **registered**
6. A call to `a1.next()` **forcefully** pushes to all listeners 

On **second** tick "other" (non-subject) operators begin emitting

7. The `scan` operator on `b1` emits its seed value of `0`
8. The `scan` operator on `b2` emits its seed value of `0`
9. Now that both `b1` and `b2` have emitted at least one item `b` will emit `{ b1: 0, b2: 0 }`

----

Subjects are kind of weird in most, especially synchronous versions, and are without anything guarding users from making mistakes. Even when switching to an *async* subject you still don't quite get the behavior you're expecting: https://esnextb.in/?gist=f03dbde1ebe3044e6e1c020239f8c493. I think it may be important to note that when you call `subscribe`/`observe`/`reduce`  in most.js no operators from the `most.js` package itself will ever emit synchronously (list scan).

If there is more we can clarify for you,

**Comment by Lodin** [comment]
Thanks for the answer! It clarified unclear moments. It is a bit sad that most cannot work with synchronous events, but using an `async` subject looks promising!
