### ISSUE TITLE
Promise polyfill should be injectable by loaders, instead of relying on global scope pollution

### ISSUE THREAD

**Issue by rjgotten** [cujojs/most#430]
Most.js relies on ES6 Promises but does not offer a way to import a polyfill for them cleanly without polluting the global scope. This is important in particular when you are writing code that should integrate with third parties within one browser context.

For AMD loaders this can be fixed by having Most.js resolve the global `Promise` through a module. A `"most/promise"` module could be defined as simply as
```js
define([], function() { return Promise });
```
This module could then at a user's discretion be remapped using AMD `map` configuration to their own, user-defined module that can in turn provide a polyfill for Most.js to use, without requiring the user to pollute the global browser environment with a polyfill implementation written into `window.Promise`.

Surely other loaders and bundlers support similar extension points.

**Comment by davidchase** [comment]
hi @rjgotten thanks for the issue

Im not quite sure what you are asking? As you mention different loaders support ways to `map` the `Promise` constructor without polluting the global namespace whether it would be via AMD, CJS etc

There's a list of recommendations for Promise polyfills [here](https://github.com/cujojs/most#requirements)

Are you proposing to create a `most/promise` ?

**Comment by rjgotten** [comment]
I'm explicitly **not** asking you to write your own `Promise` polyfill. 
I'm asking you to add the necessary infrastructure to be able to cleanly load a polyfill _as a module dependency_ without polluting global scope.


Currently. you rely on the ES6 `Promise` being present as a global, Most.js users are thus required to polyfill it with a library that writes its `Promise` implementation to the global object, i.e. ,`window` in browsers.

I'm proposing that Most.js instead imports the ES6 `Promise` as a module, rather than rely on it being present as an implicit global. For sake of argument, let's call that module `most/promise`. The default implementation of this `most/promise` module would be a simple passthrough and would continue to return the `Promise` implementation found on the global object. The AMD version of such a module would look like what I previously demonstrated:
```js
define([], function() { return Promise });
```

As this module implements the behavior that is currently hard-baked into the Most.js library, for users that leave it alone they would continue to pull `Promise` directly from the global object and the situation would remain unchanged.

However, it enables those users that want or need to polyfill `Promise` without writing it to the global object to use the method of choice of their loader or build tools to _override or re-map_ said module, and make it point to their polyfill of choice, loading that and taking that as a dependency _instead_.

**Comment by Frikki** [comment]
@rjgotten In my experience, you can add such a polyfill yourself, e.g., https://www.npmjs.com/package/es6-promise-promise

**Comment by davidchase** [comment]
@rjgotten thanks for clarifying that for me and its a reasonable request, is there a particular reason that you want `most` to require a package for ES6 Promises rather than depending on the native promise and use a polyfill as @Frikki pointed out.

This doesn't seem like it should be a behavior the library implements for instance what if you wanted to bring you own `Array` polyfill does that require the authors of a given library to provide a package internally for Arrays rather than to rely on the global instance? Granted its a far stretch analogy but simply trying to understand your situation.

**Comment by unscriptable** [comment]
I didn't have time to test it, but I think this might do what you want, @rjgotten.  It bundles most.js with a promise shim, in this case the tiny, but blazingly fast, creed.js. 

https://gist.github.com/unscriptable/8c36447483eef5d6f6ce2d96096d3f92

Let me know if you try it.

**Comment by rjgotten** [comment]
@davidchase 
> is there a particular reason that you want most to require a package for ES6 Promises rather than depending on the native promise and use a polyfill as @Frikki pointed out.

I spelled the exact reason out before:
> Most.js relies on ES6 Promises but does not offer a way to import a polyfill for them cleanly without polluting the global scope. This is important in particular when you are writing code that should integrate with third parties within one browser context.

By loading an ES6 Promise polyfill _as a module dependency_ you can avoid having to place it on the global scope as `window.Promise` where Most.js currently looks for it.

@unscriptable 
That's not what I meant.

**Comment by Frikki** [comment]
@rjgotten Use a build process such as webpack or whatever and you shouldn’t have an issue:

```
plugins: [
  new webpack.ProvidePlugin({
    Promise: 'es6-promise-promise'
  })
]
```

I’m sure you can figure out to do the same with another builder and polyfill.

**Comment by axefrog** [comment]
I don't understand why it's considered "pollution" to have Promise in the global scope. Why is that polluting the global scope, but all other standard native types are not pollution? Promise is found in the global scope in every modern JavaScript VM. Asking for it to not be in the global scope sounds like asking for special behaviour that deviates from the modern standard.

**Comment by unscriptable** [comment]
Hey @rjgotten,

> It also continues to write itself into the global scope, so it doesn't solve the original problem either.

Hmmm... I don't think it does.  I didn't test the resulting code, but it certainly looks like it doesn't pollute the global scope to me.  Unless I'm missing something, it looks like it creates a module-scoped `Promise` instance, and since most.js doesn't specifically look in the global scope, it uses it.  No???

> Thanks, but that's not what I meant. You picked one Promise polyfill and baked it directly into the library, which means users no longer have a choice of which polyfill to use. 

Personally, I think this is the best way to allow people to use a local implementation of a *normally* global object.  If Promises were just another third-party utility, then I'd be 100% agreeing with you.  However, they're equivalent to `Array`, `RegExp`, etc. now.  

I know it kinda sucks dealing with browsers, but library authors need to work towards standards and the future. :)

**Comment by rjgotten** [comment]
> I don't understand why it's considered "pollution" to have Promise in the global scope. Why is that polluting the global scope, but all other standard native types are not pollution?

Because it's not a native type, @axefrog. It just aims to act like one as much as possible and it takes the place of the native type. If you operate in a hostile and unpredictable environment where code belonging to many third-parties can and will need to co-exist, such as is the case in the browser, this is always a risk of breakage. 

(Show of hands please; who has in the past at one time or other had to deal with integrating broken third-party code that carried its own copy of jQuery? You guys will understand what I'm talking about.)


> Use a build process such as webpack or whatever and you shouldn’t have an issue:

@Frikki , the only thing that will do is include a Promise polyfill via your loader/bundler. As long as Most.js doesn't take Promise via a module dependency but only looks for the native Promise on the global object, it will continue force its users to use a Promise polyfill that publishes itself globally as `window.Promise` with the risk of breaking other code.


> I didn't test the resulting code, but it certainly looks like it doesn't pollute the global scope to me. Unless I'm missing something

Apologies to @unscriptable who is right.

I initially got hung up on lines https://gist.github.com/unscriptable/8c36447483eef5d6f6ce2d96096d3f92#file-most-with-creed-js-L1446-L1464 but those will publish the polyfill globally only if `global` or `self` exists.

If you're running this code in a browser environment that would actually implement the `global` keyword it would be able to publish the polyfill, but that is a moot point since such a browser has yet to be conceived and would naturally also implement the native `Promise` type anyway.

There's still some danger in bad third party code aliasing the browser's `window` object as `self` or `global`, though. Sadly that still happens, e.g. , with non-technical staff from marketing copy&paste-assembling their own script snippits to inject via e.g. Google's Tag manager.

**Comment by unscriptable** [comment]
Hey @rjgotten.  After looking again, I don't think my solution works.  [These lines](https://gist.github.com/unscriptable/8c36447483eef5d6f6ce2d96096d3f92#file-most-with-creed-js-L1462-L1464)(`if (typeof Promise !== 'function') { shim(); }`) should be after [this line](https://gist.github.com/unscriptable/8c36447483eef5d6f6ce2d96096d3f92#file-most-with-creed-js-L5971)(`var Promise = CreedPromise`) for it to work the way I planned. :/  You could put a `var Promise = function phony () {}` at the top of the file to bypass the test for `Promise`, I guess, but it's getting pretty messy now. :(  

Hope you find a solution that works for you.  :)

**Comment by unscriptable** [comment]
I updated the gist with my most recent suggestion, so the links to it might be off a bit.  Silly gist.

**Comment by rjgotten** [comment]
> What do you mean it’s not a "native type"? 

Because the _polyfill_ is not the native Promise type. I thought that much could be inferred from how I worded it. 

Apart from subtle behavioral differences, there's also the fact that (badly written) third-party code may sniff for things like `window.Promise` existing to determine if a browser is modern enough to support certain *other* features, which obviously will not be there if it's just a Promise polyfill.

**Comment by TylorS** [comment]
Hello @rjgotten thanks for opening up the discussion for your issues and elaborating a bit more on your use case and needs. I believe we understand what it is you'd hoped for us to allow.

However, I don't think this is a common enough use case for `most` to cater for. It seems to me to be an unfortunate case of *where* and *with what* you are required to work with. Making this exception would also open a door to adding other use case specific *hacks* which is not great for other users or for contributor maintenance. I apologize for having to say no on this particular issue, but hopefully this doesn't keep you from wanting to use the library in the future.

**Comment by rjgotten** [comment]
> hopefully this doesn't keep you from wanting to use the library in the future

No problem. It just means 15 minutes of work on my end to modify the unminified dist file. It just would've been nice to have it in the official distribution and avoid the slog of patching it in on every version update.
