### ISSUE TITLE
method for creating observables

### ISSUE THREAD

**Issue by ottonascarella** [cujojs/most#450]
Hi there,

Most reactive libs like RxJS and XStream have a create method for this, which does not seem to exist (anymore) in this library.

If there's another way to create custom observables, which certainly there is, that should be more explicit in the documentation imho, don't you agree?

**Comment by davidchase** [comment]
Hello @ottonascarella thanks for the issue 

> have a create method

Im guessing you are looking for https://github.com/mostjs/create 

we have listed here under our packages docs https://github.com/cujojs/most/blob/master/PACKAGES.md

hope this helps 😄

**Comment by ottonascarella** [comment]
Thanks, @davidchase 

I did not notice that package, really...maybe because I assumed create should be of such importance that it'd be in the main package.
