### ISSUE TITLE
Scan emits `undefined` when no initial value provided

### ISSUE THREAD

**Issue by 1ven** [cujojs/most#462]
### Summary

When running `scan` without initial value, it emits `undefined` as a first value. Or it's correct behaviour and I'm understanding it wrong?

### Expected result

It should not emit `undefined` when no initial value provided.

### Versions

- most.js: `1.5.0`

### Code to reproduce
```
// Emits `undefined` first
stream$.scan((acc, fn) => fn(acc));
```

**Comment by briancavalier** [comment]
Hey @1ven.  The initial value is a required parameter.  The convention in [the docs](https://github.com/cujojs/most/blob/master/docs/api.md#scan) is that unless a parameter is explicitly called out as optional, it's required.  Perhaps it's a bit more obvious in [`scan`'s type definition](https://github.com/cujojs/most/blob/master/type-definitions/most.d.ts#L134), though.

So, as things go in JS, by not passing a value, you're implicitly passing `undefined`, and `scan` always produces it's initial value as its first event.

Sorry for any confusion.  Hope that helps.

**Comment by 1ven** [comment]
Hi, now it's clear, thanks for clarification :)

**Comment by briancavalier** [comment]
Great, glad that helped.

**Comment by 1ven** [comment]
The problem is solved by using `.skip(1)` method
