### ISSUE TITLE
Support the async iteration proposal

### ISSUE THREAD

**Issue by ray851107** [cujojs/most#481]
It would be useful if `most.generate` supports [Async generator functions](https://github.com/tc39/proposal-async-iteration#async-generator-functions).

For example:
```javascript
async function* readLines(path) {
  let file = await fileOpen(path);

  try {
    while (!file.EOF) {
      yield await file.readLine();
    }
  } finally {
    await file.close();
  }
}

most.generate(readLines, path) // returns a Stream of lines

```

**Comment by briancavalier** [comment]
Hey @ray851107, thanks for the suggestion.  Rather than having `generate()` support two types of things, and given that Async Iteration is still just a stage-3 (last I checked), I think this would make a great [community lib](https://github.com/mostjs-community).

Would you be up for contributing?

**Comment by ray851107** [comment]
Sure!

**Comment by briancavalier** [comment]
Awesome, thank you.  Have a look at [`@most/package-starter`](https://github.com/mostjs/package-starter) as a project starting point, with our standard tooling, etc. and feel free to drop by [gitter](https://gitter.im/cujojs/most) if you have any questions.

I'll close this issue, but feel free to continue discussion here as well.

**Comment by ray851107** [comment]
Hi @briancavalier , I created a package at https://github.com/ray851107/most-async-iterable

Should I move the repo to most-community?

**Comment by briancavalier** [comment]
Nice work, @ray851107.  It looks really cool.

Open an issue in the [mostjs-community/about repo](https://github.com/mostjs-community/about) asking to become a member of the GitHub org, and we'll send you an invite.  Once you've accepted the invite, you can transfer the repo into the mostjs-community org.  After you transfer it, you'll still retain ownership of the repo.

Just to be clear: it's entirely voluntary.  You're absolutely welcome to keep the repo in your personal GitHub account.  The benefits of transferring it are more visibility, and potentially more feedback from the community.

Cheers, and thanks for contributing!
