### ISSUE TITLE
Buster test suite not maintained, should be considered deprecated

### ISSUE THREAD

**Issue by skylize** [cujojs/most#500]
The `busterjs` package appears to be no longer maintained. I discovered this because I work in Windows WSL Bash. Attempting to  `npm install` a clone of `cujojs/most` resulted in a failed attempt to install `contextify` which clearly states on it's Github page that it is no longer maintained. A bit of tracing revealed that this came from `buster-test` using a significantly outdated version of `jsdom`. Turns out that `busterjs` has not been touched in over 2 years, and it's most recent version 0.8.0 was never even published to `npm`. 

I'm sure switching test suites will be painful, but you should at least start making plans for making a switch.

The `contextify` package was marked as an optional dependency, so had no harmful effect on installing dependencies (just a lot of noise in the terminal). So feel free to close this issue if you don't need it as a reminder to work on switching test suites.

**Comment by briancavalier** [comment]
Yes, thanks. This is known. We’ve already switched in `@most/core`, so we probably won’t put any effort into switching here until most 2.0 (which will be built atop `@most/core`). Like you said, it’s unfortunate and noisy, but currently works.
