### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [cujojs/most#509]
Hi @briancavalier
We would like to [add ](https://github.com/cdnjs/cdnjs/issues/8143)you library to cdnjs hosting
Should we host libraries before v0.15.0?
If we are, please provide name of files that we have to host from lib folder
Thanks for cooperation

**Comment by briancavalier** [comment]
Hey @sashberd.  It looks like [most is already hosted on cdnjs](https://cdnjs.com/libraries/most).  I don't think we need to host versions before 0.15.0.  Is there anything else that needs to be done?

Cheers

**Comment by sashberd** [comment]
@briancavalier Thanks.
