### ISSUE TITLE
Speed when using DOM compared to virtual DOM

### ISSUE THREAD

**Issue by frankymacster** [cujojs/most#528]
Hi,

How does the speed compare with React virtual DOM when using 
 Most.js with DOM elements?

**Comment by davidchase** [comment]
Hi @frankymacster can you help me understand what exactly you are asking ? Are you trying to compare the performance of most dom events to react dom events ? Or something else ?

**Comment by frankymacster** [comment]
@davidchase Sorry for not having been so clear. I meant in terms of performance in the rendering of the DOM.

How does using most.js with HTML elements compare with using a virtual DOM to diff between changes that need to be applied to the actual DOM in terms of rendering?

In the examples (https://github.com/mostjs/examples) pointers to DOM elements are used and modified after the state changes. Will the DOM only be rerendered at that element?

I am trying to compare most.js and cycle.js and saw that cycle.js uses a virtual dom for rendering while most.js doesn't. I was wondering if this can make most.js less performant in terms of rendering.

Thanks

**Comment by davidchase** [comment]
No worries @frankymacster  😄 
So Most.js is an events based library without an specific tie to any DOM virtual or not, so you can choose any.
While cycle.js is closer to a framework which provides a vDOM which is based on [snabbdom](https://github.com/snabbdom/snabbdom). 
If im not mistaken you can actually use [Most.js with cycle.js](https://cycle.js.org/api/most-run.html).

Hope my answer helps. let me know if i can help some more.

**Comment by frankymacster** [comment]
Oh I wasn't aware of '@cycle/most-run'.
I think this is what I was looking for.
I want to stay as close as possible to using monads for streams (which I'm not completely sure cycle.js does) but still being able to work with a virtual DOM.

Thanks a lot! :)

**Comment by briancavalier** [comment]
Hey @frankymacster, in addition to @davidchase's excellent answer, you may also want to check out [`@most/core`](https://github.com/mostjs/core).  It's the next version of most, and we recommend it for new projects.  Updated [docs are here](https://mostcore.readthedocs.io), and there are some simple examples in the GitHub repo.  As already mentioned, it can be used with whatever DOM library you prefer, and along those lines, there is a [todomvc example using `@most/core` and react](https://mostcore.readthedocs.io).

Cheers!
