### ISSUE TITLE
Benchmark against Flyd

### ISSUE THREAD

**Issue by Mapiac** [cujojs/most#529]
Has Most.js ever been benchmarked against Flyd?

Just wondering if this lib has ever been benchmarked against Flyd in perf and mem testing? It appears faster than Kefir but curious I find no Flyd reference. https://github.com/paldepind/flyd/issues/22

More so are there some unique reasons to use one over the other?

Tnx

**Comment by briancavalier** [comment]
Hi @Mapiac.  We've not benchmarked flyd, but it'd probably be fairly easy to add to the benchmarking suite if you're interested in either contributing that, or just trying it.  I'd urge you to consider benchmarking [`@most/core`](https://github.com/mostjs/core).  It's the new version of most, and we encourage everyone to use it for new projects.

As for unique reasons, I'm not familiar enough with flyd to speak to it's strengths.  We believe that `@most/core`'s strengths are its commitment to a lean, declarative API, relatively small size and tree-shakeability, and of course, it's cpu and memory performance.

I'd say read the [concepts](https://mostcore.readthedocs.io/en/latest/concepts.html), look at [examples](https://mostcore.readthedocs.io/en/latest/getting-started.html#examples), and peruse the [API](https://mostcore.readthedocs.io/en/latest/api.html#most-core).

Hope that helps.  Cheers!

**Comment by Mapiac** [comment]
Thanks so much for that Brian. Adding these screen shots from Flyd creator, for if it helps others making similar comparissisons. We might have some benchmarks to add soon. Most.js looks great and we'll definitely look to use the core version.

**Comment by briancavalier** [comment]
My pleasure, @Mapiac.

Shall we close this issue and plan to open a PR if you move forward with contributing new benchmarks to `@most/core`?
