### ISSUE TITLE
Just want to share most-koans I've built like 3 of years ago

### ISSUE THREAD

**Issue by vyorkin** [cujojs/most#530]
https://github.com/vyorkin/most-koans

> The Most.js Koans are a fun and easy way to get started with this awesome reactive programming toolkit. No experience assumed or required. Just follow the instructions below to start making tests pass!

Just letting you know in case you want to add a link to the README. But I'm not sure if it still works as expected (and if it's actually a good way to learn about most.js). Feel free to close the issue. Thanks!

**Comment by briancavalier** [comment]
Hey @vyorkin, this is super-cool.  Thank you for creating it and for sharing it!

Would you be interested in porting it to use [`@most/core`](https://github.com/mostjs/core)?  I'd be willing to help, and I imagine other core team members may be able to pitch in as well.

Also, would you be open to donating that ported version to [mostjs-community](https://github.com/mostjs-community)?  You'd retain ownership of the project and repo, and it would likely have more visibility to the community.

Let us know what you think, and thank you again!

**Comment by vyorkin** [comment]
Yeah, sure, I'd like to help porting it. I've just transfered the ownership of `most-koans` to the [mostjs-community](mostjs-community).

**Comment by briancavalier** [comment]
Awesome, thank you!  I'll try to get into it a bit soon as well.
