### ISSUE TITLE
fromPromise is not disposed correctly

### ISSUE THREAD

**Issue by marcus13371337** [cujojs/most#534]
### Summary
Creating a stream with `fromPromise` and then unsubscribing to it, most will execute the sequential steps even though the stream should be disposed

As example:
```js
    most
      .fromPromise(new Promise(resolve => setTimeout(resolve, 2000)))
      .tap(() => console.log('1'))
      .merge(most.just().delay(1500)) // since 1500 < 2000, the fromPromise-stream should be unsubscribed at 1500 and any result after that should be ignored
      .take(1)
      .subscribe({
        next: () => console.log('Finished'),
      })
```

### Expected result
`console.log('Finished')`

### Actual Result
`console.log('Finished')`
`console.log('1')`

### Versions

Seems to have been introduced when the following refactor was done:
https://gist.github.com/briancavalier/a27ddc247dd118ae5508

- most.js: 1.7.2

### Steps to reproduce

See above

### Code to reproduce

```js
    most
      .fromPromise(new Promise(resolve => setTimeout(resolve, 2000)))
      .tap(() => console.log('1'))
      .merge(most.just().delay(1500)) // since 1500 < 2000, the fromPromise-stream should be unsubscribed at 1500 and any result after that should be ignored
      .take(1)
      .subscribe({
        next: () => console.log('Finished'),
      })
```

**Comment by briancavalier** [comment]
Hey @marcus13371337, thanks for the detailed report and example.  I just opened a candidate fix in https://github.com/cujojs/most/pull/535.  Feel free to try that branch to see if it solves the issue for you.

**Comment by briancavalier** [comment]
@marcus13371337 We published 1.8.1 with the fix.

**Comment by michaelduminy** [comment]
Thanks @briancavalier and thanks @marcus13371337 for the report

**Comment by michaelduminy** [comment]
@briancavalier the CHANGELOG hasn't been updated since 1.7.2
What changed in 1.8.0?

**Comment by marcus13371337** [comment]
Thank you so much!
