### ISSUE TITLE
Make it easier to work with promise returning functions

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#54]
There's `most.fromPromise`, which is the manual way of dealing with promises, so you can do:

``` js
stream.map(functionThatReturnsAPromise).flatMap(most.fromPromise);
// or
stream.flatMap(function(x) {
   return most.fromPromise(functionThatReturnsAPromise(x));
});
```

Both of which probably get unwieldy if you have lots of promise-returning functions.  We should brainstorm some ways to make it easier.

Some thoughts:
1. RxJS automatically treats promises as observables in `flatMap`, iow you can pass a promise-returning function directly to `flatMap`.  We could do something similar, probably in `join()`.  I'm not opposed to that, just want to think through options.
2. Add a specific `stream.mapAsync(promiseReturningFunction)` API.  Does this open the door to folks requesting other `*Async` variants?
3. Add a convenience API, something like `stream.map(promiseReturningFunction).await()` that awaits promises in the stream at that point.

Other ideas?

**Comment by StreetStrider** [comment]
This is an old thread, but I'm feeling I should leave a feedback. In my opinion `most` offers good API, it's a pretty explicit and not very bloated. However, I think API should have seamless, implicit integration with promises, they must be unwrapped by default by methods like `map`, `filter`. The reality is when you pass promise down a stream you want to pass a value itself and not promise object (it is the 99% of the cases, I presume). And even if one want to work with raw promises, it is still possible by wrapping promise in `[ promise ]` and manually unwrapping it in the next steps.

If this is not enough good, API can introduce explicit `most.quote` which will work as an opposite for `fromPromise`, it will say to treat passed value (promise, observable…) literally, like quoting in lisp-world. So you don't need to wrap your promises in `fromPromise` in 99% of cases, you just need to `quote` in the rest 1% :) Win.

`await` is a good solution, but it fails on heterogenous streams, i.e the following breaks:
```js
most
.from([0,1,2])
.map(x => x ? Promise.resolve(x * 2) : 1)
.await() // ← do fancy unwrapping
.observe(console.log)
```
So it is not a solution for part of the cases.

Finally, I think implicit promise unwrapping is ok. Working in that way brings more composability, you can
```js
uri.map(request).observe(/* responses */)
```
and don't mind about unwrapping, awaiting and heterohenous streams.
