### ISSUE TITLE
good for dataflow graphs?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [cujojs/most#546]
hi, 
I just came here from a medium article on ramda.
Is this library capable of stream merging and splitting?

**Comment by briancavalier** [comment]
Hi @hp8wvvvgnj6asjm7. Yes 😄 

If possible, please use the newer [@mostjs/core](https://github.com/mostjs/core), e.g. `npm install --save @most/core`, as the `cujojs/most` repo is older and in maintenance mode.  It is a newer implementation of the same ideas in `cujojs/most`.  You can find the docs here: https://mostcore.readthedocs.io/en/latest/

For merging, see [the api docs for merge operations](https://mostcore.readthedocs.io/en/latest/api.html#merging).  For splitting, you can use [multicast](https://mostcore.readthedocs.io/en/latest/api.html#multicast) to allow a stream to be consumed by multiple consumers.

One caveat is that if you need "back pressure", aka flow control, then you may want to look into other options.  Both `@most/core` and `cujojs/most` are intended to deal with events as they happen.

I hope that helps.

I'll close this issue, but please feel free to continue the discussion if you need.
