### ISSUE TITLE
Side-effect at end of stream

### ISSUE THREAD

**Issue by elmpp** [cujojs/most#551]
### Summary

Bit of a newb question here but is there a better way than this to perform side-effect at end of stream?

```
const applyCallbackToEndOfStream = (cb: Callback, stream: most.Stream<any>) => {
  return stream.continueWith(() => {
    most.of('').tap(() => cb())     // <--------  could also be a `drain().then(() => {})` or similar
  })
}

const createStream1 = (cb: Callback) => applyCallbackToEndOfStream(cb, most.of(reduxAction1_1, reduxAction1_2))
const createStream2 = () => most.of(reduxAction2_1, reduxAction2_2)

const mainStream = most.from([reduxAction1, reduxAction2]).concatMap(() => {
  return most.concat(
    createStream1(() => console.log('fired after Stream1'),
    createStream2()
  )
}
```

Note that i'm writing "Epics" in a large commercial app so don't have access to the observation code

**Comment by briancavalier** [comment]
Hey @elmpp, thanks for the question.  It probably depends on the situation, but using `continueWith` is certainly a reasonable way.  At the top level, you can also use the promise returned by `drain`.  You could potentially do that in your case as well, as you mentioned, combined with fromPromise if you want to turn it back into a stream.

Hope that helps!

BTW, if you're working on a codebase that isn't heavily tied to `most`, you may want to have a look at [`@most/core`](https://github.com/mostjs/core).
