### ISSUE TITLE
Add delayed(delayTime, value)

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#75]
See #74.  Similar to the proposed `periodic(period, value)`, `delayed(delayTime, value)` is kind of the single-value equivalent.  I can see it being very useful with `until`, `since`, and `during`.

One potential problem is that we have `most.delay(delayTime, stream)` and `stream.delay(delayTime)` which are similarly named, but do something different: they timeshift a whole stream "to the right" by `delayTime`.

**Comment by aronallen** [comment]
what about calling it ```later(delayTime, value)``` or ```postpone(delayTime, value)```

**Comment by TylorS** [comment]
Seems like this is just

```js
function delayed (delayTime, value) {
  return most.just(value).delay(delayTime)
}
```

Not sure that this really warranted to be in the main library

**Comment by briancavalier** [comment]
This exists now in `@most/core` as [at](https://github.com/mostjs/core/blob/master/docs/api.rst#at) (along with associated stream-local time changes).  So, it'll be in most 2.0.
