### ISSUE TITLE
[question] flatMapError

### ISSUE THREAD

**Issue by davidchase** [cujojs/most#79]
Hi, quick question

So here's my setup
```
var rest = require('rest');
var mime = require('rest/interceptor/mime');
var most = require('most');
var client = rest.wrap(mime);

var stream1 = most.fromPromise(client({path:'http://reqr.es/api/users?page=3'}));
var stream2 = most.fromPromise(client({path:'http://reqr.es/api/users/23'}));

stream1.concat(stream2)
.flatMapError(function(e){
   return most.of('hello');
})
.observe(console.log.bind(console));
```
So `stream2` will fail with a `404` error not found.

Shouldn't my `console.log` then show the successful data from `stream1` and `hello` ?

Thank you for the help in advanced

**Comment by briancavalier** [comment]
Hey @davidchase, are you using rest.js's [error interceptor](https://github.com/cujojs/rest/blob/master/docs/interceptors.md#error-code-interceptor)?  By default, rest.js considers *any* response to be successful, so the promises it returns will always fulfill, *unless* you ues the error interceptor to define that 404 (or whatever codes you want/need) should represent a failure.

If you verify that the promise *is* rejecting and `flatMapError` still isn't kicking in, then we def need to dig deeper here.  Let me know!

**Comment by davidchase** [comment]
@briancavalier thanks for the quick reply
it seems like if i add `rest.wrap(mime).wrap(errorCode);` 

I just get the one successful stream logging and the other logged message is `Potentially unhandled rejection` but no 'hello'

**Comment by briancavalier** [comment]
Thanks @davidchase.  Seems like it could be a bug.  I'll look into it!

**Comment by briancavalier** [comment]
Ok, yep, it's a (braindead!) bug in `fromPromise`.  It isn't propagating an error when the promise rejects.  I'll pull together a fix release asap, probably later tonight.  Thanks for reporting this!

**Comment by davidchase** [comment]
Thanks for looking into it :+1:

**Comment by briancavalier** [comment]
Ok, fix for `fromPromise` (and unit test), is in master in c55c057.  I still need to fix `await` as well.

**Comment by briancavalier** [comment]
In master, both `fromPromise`, and `await` should correctly handle rejected promises.  Please try them out, and let me know if you run into any other issues.

I'll plan to do a release over the weekend.  I had more plans for 0.11.0, but this is important enough to warrant releasing 0.11.0 now (rather than 0.10.3, since there have been some significant changes since 0.10.2).  We can include the other upcoming new things in 0.12.0.

Thanks again, @davidchase!
