### ISSUE TITLE
Switch to eslint

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#81]
I think it's time to start exploring some other/newer tools.  ESLint seems like it's quite usable now, so we should at least try it.

**Comment by jeffrose** [comment]
jscs seems to be gaining traction as well.

https://www.npmjs.com/package/jscs

**Comment by briancavalier** [comment]
Interesting, thanks for the link.  It looks like they could be complimentary: eslint for warnings/errors and jscs for code style?

**Comment by jeffrose** [comment]
Yes, though there is some overlap in functionality.

**Comment by briancavalier** [comment]
Closing, since we switched a while ago to eslint.
