### ISSUE TITLE
Explore external fusion/rewrite rules, compiler

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#85]
Many pairs, triples, etc. patterns of combinators can be simplified algebraically.  For example, `s.map(f).map(g)` is equivalent to `s.map(g•f)`, where `•` is function composition.  Thus a sequence of N `map` operations can be reduced to a single `map`.  Similarly, a sequence of N `filter` operations can be reduced to a single `filter` using predicate composition (ie `p(x) && q(x)`).

More sophisticated simplifications are possible as well.  For example, `s.filter(p).map(f)` can be simplified to a "filtermap" operation, which itself then composes on the left with additional `filter` ops and on the right with additional `map` ops.  IOW `filtermap.map` can be reduced again to a single `filtermap`.

Rather than have each combinator know how to combine itself with any other combinator, I think these rules should be applied from the outside somehow.  For example, some sort of "compiler" which can analyze and "rewrite" combinator sequences.  It could be built from an extensible set of matching rules, where each rule is able to recognize a specific combinator sequence, such as `.map.map` and substitute a simplified/optimized replacement.

**Comment by briancavalier** [comment]
I've done some initial experiments, and the performance benefits can be significant in some cases.  For example, adjacent filter predicate composition seems to make a huge difference.  In other cases, though, the gains are less significant, such as adjacent map composition.  Still others seem to actually make things worse (maybe my test implementations were crummy), such as turning `.map.filter` into a "mapfilter".

**Comment by briancavalier** [comment]
[Here are some initial results](https://gist.github.com/briancavalier/9393d0c9e9e4055629c8) run on io.js 1.4.2.  This test used fusion rules for map.map, filter.filter, and filter.map, and can fuse any number of adjacent filter/map.  For example, the last run in the gist fuses filter.filter.map.map, i.e. 4 steps, into a single step.

**Comment by unscriptable** [comment]
Nice! I did not suspect this much performance gain. It seems like filter fusion is a especially substantial benefit. 

So… what are the downsides?  How's the performance of the fusion-compile step? Is it negligible?  Is there a way to disable the fusion step for CSP environments?  Do we care about CSP environments? :)

**Comment by unscriptable** [comment]
After re-reading the OP, I may have misunderstood. Are you fusing the source codes of the filter and nao functions? Or are you just using some
form of function composition?

**Comment by briancavalier** [comment]
> Are you fusing the source codes of the filter and map functions? Or are you just using some form of function composition?

I've tried a few different things.  So far plain old function/predicate composition is the simplest and gives the best results--no crazy source/AST rewriting.

> Nice! I did not suspect this much performance gain. It seems like filter fusion is a especially substantial benefit.

The results surprised me too, honestly!  Yeah, filter + filter gives a big benefit, and so does filter + map.  map + map is not as significant, but still a benefit.

One thing I don't like about the current approach is that it's coded directly into filter and map :/  I'd much rather it be external, but since it isn't really a visible change (i.e. it doesn't affect the API), it's probably ok just to go with it as is.  We could release it, and then figure out a nice way to externalize it.

**Comment by briancavalier** [comment]
I just pushed the [x-add-fusion](https://github.com/cujojs/most/tree/x-add-fusion) branch with the fusion approach that generated the results in the [gist above](https://github.com/cujojs/most/issues/85#issuecomment-76566029).  Again, I'm not really happy with this from an architecture standpoint, but it proves the concept.

**Comment by unscriptable** [comment]
It seems like this would reduce memory consumption, too.

**Comment by briancavalier** [comment]
It'd def be interesting to measure the difference! If it does reduce mem, then it's a double win. I'm really not sure, since it trades a couple objects (an extra source and sink) for a scope capture (a very small scope capture, tho).

I'll try to make some time to measure it.

**Comment by briancavalier** [comment]
Tracking this now in #92.
