### ISSUE TITLE
Consider deprecating most.fromEventWhere

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#86]
The main motivation for `most.fromEventWhere` was that prior to 0.10, event propagation was async, and so `most.fromEvent(...).tap(e => e.preventDefault())` did not work.

Since 0.10, event propagation is synchronous whenever possible.  In particular, in constructs like `most.fromEvent(...).filter(f)`, or `most.fromEvent(...).tap(f)`, `f` will always be called in the call stack in which events originate.  That means, for example, `most.fromEvent(...).tap(e => e.preventDefault())` will work as expected.

Should we deprecate `most.fromEventWhere`?

**Comment by unscriptable** [comment]
In what situations might a lambda (predicate, etc) be called async?  Is it only when the dev introduces a promise into the stream?

**Comment by briancavalier** [comment]
The only situation is when you explicitly use a combinator that is naturally async, like `delay`, `await`, etc.  Other combinators are always sync.  Some are less obvious than others, like `flatMap(f)`, which is async because `f` must return a stream, and streams always start async.

However, one key in this specific case is that using `filter` or `tap` immediately "to the right" of `fromEvent` will *always* be in the same call stack.  Those are the two you'd most likely use to do a selector match or `preventDefault`.  Doing them in succession would also always be sync: `domEvents.filter(selectorMatch).tap(preventDefault)` ... i.e. only preventing default on matching events.

**Comment by briancavalier** [comment]
Deprecated in #91.
