### ISSUE TITLE
Are there any plans for `fromNodeStream` or a `pipe`?

### ISSUE THREAD

**Issue by nackjicholson** [cujojs/most#93]
First of all, I've tinkered around with RxJS, as well as Highland, and I prefer most because of the way it nails the interaction with promises. Also, your docs with the stream diagrams are just miles above the other two.

Second, I'm using most in nodejs, and I'm wondering if you have any thoughts about whether node streams have a future in most. I've been able to use `most.create` to get stream data through a most stream, but there really needs to be a way to pipe a most through another node stream. As well as ways to handle back pressure. Otherwise it's not really very useful, reading from a large node stream is like a firehose, and it will fill up the internal buffer and grind node to a halt after a while.

Have you had any thoughts about adapting most to node streams? Is there any priority on additions like this? I am happy mixing and matching with highland, but like I said -- I much prefer most, and it would be great to be able to do things like this with it. Maybe if I have some time I'll try to learn the concepts you have around "sources" and "sinks" to see if I can fork this repo and add something. Any guidance on that front would be greatly appreciated.

Cheers!

**Comment by nackjicholson** [comment]
Here is a link to an open issue RxJS has about the same issue in case you're curious. They have node adapters, but they don't solve the large stream back pressuring either. https://github.com/Reactive-Extensions/RxJS/issues/508#issuecomment-77513715

**Comment by briancavalier** [comment]
Hey @nackjicholson, thanks for the kind words.

This question has come up a few times.  In my original vision for most.js, I didn't have any plans to deal with node data streams, or any data streams for that matter.  However, it seems like people would find it to be useful, so I'm coming around to being ok with it :)

I've done a bit of investigation, and even [a prototype that uses promises communicated from consumer to producer to indicate demand](https://github.com/cujojs/most/blob/node-read-adapter/lib/source/fromReadableStream.js) (basically as a "stop producing until this promise fulfills" signal).  The prototype works well, but I didn't push it too far ... propagating promises in the reverse direction would get tricky in certain combinators.

I think there needs to be more investigation into other ways to communicate demand.  For example, I could see packaging up the `sink` and `scheduler` arguments into a `subscription` object which provides a communication channel from consumer to producer.  That `subscription` could provide an API similar to node's pause/resume, or something more sophisticated like the `request(N)`/`cancel()` API specified in the [reactive-streams spec](https://github.com/reactive-streams/reactive-streams-jvm#3-subscription-code).

In the end, the demand communication would need to be implemented in most.js core, but I could see the adapter itself potentially being an add-on that lives in a contrib repo.

Any thoughts on all of that?

**Comment by briancavalier** [comment]
>  Maybe if I have some time I'll try to learn the concepts you have around "sources" and "sinks" to see if I can fork this repo and add something. Any guidance on that front would be greatly appreciated.

Great!  I would more than happy to answer questions if you start to dissect the architecture.  I haven't had time to document it yet, unfortunately.  Here's a bit of info, off-the-cuff:

**Stream**

Stream is just a wrapper around a source, and provides a prototype on which public-facing APIs live.

**Source**

A source represents a view of events over time.  It has a single method, `run(sink, scheduler)` which arranges to propagate events to the provided `sink`.  If it needs to deal with time, it can use `scheduler`, which has methods for knowing the current time, and scheduling future tasks in a more performant way than using `setTimeout` directly.

A source's `run` method must return an object with a `dispose` method--similar in concept to RxJS's `Disposable`.

Some sources are simple and just store parameters which get passed wholesale to a sink.  Other sources do more, especially in the case of sources that need to combine multiple streams, or deal with higher order streams.

Some sources ultimately *produce* events, such as from DOM events.  These producer sources *must never* produce an event in the same call stack as their `run` method is called.  IOW, they must begin producing items asynchronously.  In some cases, this comes for free, such as DOM events.  In other cases, it must be done explicitly, such as values from an array.

**Sink**

A sink receives signals, typically does something with them, such as transforming or filtering them, and then propagates them to another sink.  It has 3 methods, each corresponding to a type of signal: `event(t, x)`, `end(t, x)`, and `error(t, e)`, where `t` is a time, `x` is a value, and `e` is likely an Error of some sort.

Typically a combinator will be implemented as a source and a sink.  The source is usually stateless/immutable, and creates a new sink for each new stream observer.  In most cases, the relationship of stream to source is 1-1, but source to sink is 1-many.

**Comment by nackjicholson** [comment]
Thanks for all the great info! So glad I asked. I'll probably read and re-read it several times.

I'm working on a team that is just starting to use most, but we're finding it to be excellent. Code looks better, reads better, module separation becomes easier. I'll share this with everyone and hopefully as our need rises to process node data streams we'll feel more and more pressure to help you out with this :)

**Comment by nackjicholson** [comment]
Never did any work on this, never will :)

**Comment by kaosat-dev** [comment]
Too bad,  I might take up the torch at some point then ! 
I have been using `most` for a while now, but had to use streams for very performance/memory sensitive uses, and would kill to be able to interface with node.js streams.

**Comment by TylorS** [comment]
@kaosat-dev His write up above is 100% still correct. It's also been more formally documented in our wiki [here](https://github.com/cujojs/most/wiki/Architecture).

**Comment by kaosat-dev** [comment]
thanks a lot for the very quick reply @TylorS !
Some of it goes above my head, but I'll try and dig using the wiki & Brian's prototype as a basis.

**Comment by briancavalier** [comment]
Hey @nackjicholson, been a while :) hope all is well.

@kaosat-dev Thanks for jumping in and offering to help here.  Feel free to discuss in the [gitter chat](http://gitter.im/cujojs/most).  In addition to the core team, there are lots of knowledgable folks in there who have contributed to [mostjs-community](https://github.com/mostjs-community).

**Comment by kaosat-dev** [comment]
@briancavalier  sorry for the late reply, thanks , I'll ask around in the gitter chat, been lurking there for a long time now :) Thanks for the infos, I was not aware of mostjs-community , quite a goldmine and a good place to start from !
